### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by sneznat** [ImYanXiao/Elaina-MultiDevice#118]
![Screenshot_2023-08-29-15-31-09-971_com android chrome](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/110214957/3e1e9737-48de-4c3a-8254-449af0e848c7)
Error bang

**Comment by ImYanXiao** [comment]
> ![Screenshot_2023-08-29-15-31-09-971_com android chrome](https://user-images.githubusercontent.com/110214957/263953600-3e1e9737-48de-4c3a-8254-449af0e848c7.jpg) Error bang

Owalah bentar yak

**Comment by ImYanXiao** [comment]
Done

**Comment by ImYanXiao** [comment]
Klo ada error lgi open aja

**Comment by sneznat** [comment]
> Klo ada error lgi open aja

Wakatta
