### ISSUE TITLE
Antispam

### ISSUE THREAD

**Issue by Xnuvers007** [ImYanXiao/Elaina-MultiDevice#120]
Kayaknya butuh antispam deh, banyak user ngespamming

**Comment by Xnuvers007** [comment]
sama ini error

![gambar](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/62522733/41e682ae-7eae-45bb-945f-bb01d4005c6b)

**Comment by Xnuvers007** [comment]
> sama ini error
> 
> ![gambar](https://user-images.githubusercontent.com/62522733/264506317-41e682ae-7eae-45bb-945f-bb01d4005c6b.png)

udah gw fix, btw tambahin antispam Xiao @ImYanXiao

**Comment by ImYanXiao** [comment]
> > sama ini error
> > ![gambar](https://user-images.githubusercontent.com/62522733/264506317-41e682ae-7eae-45bb-945f-bb01d4005c6b.png)
> 
> udah gw fix, btw tambahin antispam Xiao @ImYanXiao

Lagi" apa? Yak benul malas :v

**Comment by Xnuvers007** [comment]
> > > sama ini error
> > > ![gambar](https://user-images.githubusercontent.com/62522733/264506317-41e682ae-7eae-45bb-945f-bb01d4005c6b.png)
> > 
> > 
> > udah gw fix, btw tambahin antispam Xiao @ImYanXiao
> 
> Lagi" apa? Yak benul malas :v

Udah gw fix , yang antispam Adain lagi Xiao

**Comment by Xnuvers007** [comment]
@ImYanXiao

**Comment by ImYanXiao** [comment]
> @ImYanXiao

Udah anjir :v

**Comment by Xnuvers007** [comment]
Wokeh :v
