### ISSUE TITLE
Help :V

### ISSUE THREAD

**Issue by Xnuvers007** [ImYanXiao/Elaina-MultiDevice#123]
@ImYanXiao coba dah cek downloader-pinterest.js liat commentnya. di wa web muncul video dan gif yang di kirim, tapi di wa biasa ga ada, cuman bisa gambar doank...

**Comment by ImYanXiao** [comment]
> @ImYanXiao coba dah cek downloader-pinterest.js liat commentnya. di wa web muncul video dan gif yang di kirim, tapi di wa biasa ga ada, cuman bisa gambar doank...

Bejir bat, pantesan gw di marahin anjir salah gw apacoba :v

**Comment by ImYanXiao** [comment]
Gegara masih pke sendButton keknya, kan udh ga work button di wa

**Comment by Xnuvers007** [comment]
> Gegara masih pke sendButton keknya, kan udh ga work button di wa

Itu udah gw ubah jadi sendFile, gada sendButton juga

**Comment by ImYanXiao** [comment]
> > Gegara masih pke sendButton keknya, kan udh ga work button di wa
> 
> Itu udah gw ubah jadi sendFile, gada sendButton juga

Masih ttp juga?

**Comment by Xnuvers007** [comment]
> > > Gegara masih pke sendButton keknya, kan udh ga work button di wa
> > 
> > 
> > Itu udah gw ubah jadi sendFile, gada sendButton juga
> 
> Masih ttp juga?

Hooh, coba dah download images, video, gif. Images bisa + keliatan di android + desktop

Video gif, di desktop ada tapi di android gada

**Comment by Xnuvers007** [comment]
@ImYanXiao Gw ada saran, beberapa plugins mending dijadiin satu aja kayak yang gw buat ini, biar gak banyak files https://github.com/ImYanXiao/Elaina-MultiDevice/blob/master/plugins/tool-shorturl_kursuang.js

jadi enak nantinya. saran aja sih

**Comment by Xnuvers007** [comment]
@ImYanXiao ini replit gabisa pairing code ? atau dulu gimana biar bisa pairing code ? plugin dikurangi ?

**Comment by ImYanXiao** [comment]
Gw open gh niat"an bjirr🤣
