### ISSUE TITLE
bang lirik bang

### ISSUE THREAD

**Issue by irhanftelis** [ImYanXiao/Elaina-MultiDevice#124]
![image](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/63201597/c41ec80e-d662-45a3-9015-8626bc7e45d2)

bang ini gmna gini mulu padahal baru install belum ada sessi nya

**Comment by ImYanXiao** [comment]
Kebanyakan Plugins Berakibat Qr Tidak Muncul, Itulah Masalah pada sc ini

**Comment by Xnuvers007** [comment]
> ![image](https://user-images.githubusercontent.com/63201597/266979146-c41ec80e-d662-45a3-9015-8626bc7e45d2.png)
> 
> bang ini gmna gini mulu padahal baru install belum ada sessi nya

ubah aja di package.json
jadi gini
"@adiwajshing/baileys": "npm:baileys@^6.0.9",

**Comment by ImYanXiao** [comment]
> > ![image](https://user-images.githubusercontent.com/63201597/266979146-c41ec80e-d662-45a3-9015-8626bc7e45d2.png)
> > bang ini gmna gini mulu padahal baru install belum ada sessi nya
> 
> ubah aja di package.json jadi gini "@adiwajshing/baileys": "npm:baileys@^6.0.9",

Udh ku ganti pairingcode 🗿

**Comment by Xnuvers007** [comment]
> > > ![image](https://user-images.githubusercontent.com/63201597/266979146-c41ec80e-d662-45a3-9015-8626bc7e45d2.png)
> > > bang ini gmna gini mulu padahal baru install belum ada sessi nya
> > 
> > 
> > ubah aja di package.json jadi gini "@adiwajshing/baileys": "npm:baileys@^6.0.9",
> 
> Udh ku ganti pairingcode 🗿

Dibikin backup aja 🗿kasian yang mau fitur banyak tapi kena pairing code🗿coba gini deh akalin, plugin taro dulu di backup, sisain 1 plugin, ntar pairing code, terus masukin lagi.

**Comment by ImYanXiao** [comment]
>> > ![image](https://user-images.githubusercontent.com/63201597/266979146-c41ec80e-d662-45a3-9015-8626bc7e45d2.png)
> > > > bang ini gmna gini mulu padahal baru install belum ada sessi nya
> > > 
> > > 
> > > ubah aja di package.json jadi gini "@adiwajshing/baileys": "npm:baileys@^6.0.9",
> > 
> > 
> > Udh ku ganti pairingcode 🗿
> 
> Dibikin backup aja 🗿kasian yang mau fitur banyak tapi kena pairing code🗿coba gini deh akalin, plugin taro dulu di backup, sisain 1 plugin, ntar pairing code, terus masukin lagi.

**Comment by ImYanXiao** [comment]
> > > > ![image](https://user-images.githubusercontent.com/63201597/266979146-c41ec80e-d662-45a3-9015-8626bc7e45d2.png)
> > > > > bang ini gmna gini mulu padahal baru install belum ada sessi nya
> > > > 
> > > > 
> > > > ubah aja di package.json jadi gini "@adiwajshing/baileys": "npm:baileys@^6.0.9",
> > > 
> > > 
> > > Udh ku ganti pairingcode 🗿
> > 
> > 
> > Dibikin backup aja 🗿kasian yang mau fitur banyak tapi kena pairing code🗿coba gini deh akalin, plugin taro dulu di backup, sisain 1 plugin, ntar pairing code, terus masukin lagi.

Fix Gaperlu Hapus" Lagi, udh bisa🗿🗿
