### ISSUE TITLE
Cuy

### ISSUE THREAD

**Issue by ImYanXiao** [ImYanXiao/Elaina-MultiDevice#125]
@Xnuvers007 Bantu Kurangin Fitur yg nggk digunain, biar bisa muncul code pairing

**Comment by irhanftelis** [comment]
kabarin bang klo uda jadi:v

**Comment by Xnuvers007** [comment]
> @Xnuvers007 Bantu Kurangin Fitur yg nggk digunain, biar bisa muncul code pairing

lagi capek gw :V
nanti deh

**Comment by ImYanXiao** [comment]
> > @Xnuvers007 Bantu Kurangin Fitur yg nggk digunain, biar bisa muncul code pairing
> 
> lagi capek gw :V nanti deh

Gw bingung mo gw hapus yg mana🗿

**Comment by Xnuvers007** [comment]
> > > @Xnuvers007 Bantu Kurangin Fitur yg nggk digunain, biar bisa muncul code pairing
> > 
> > 
> > lagi capek gw :V nanti deh
> 
> Gw bingung mo gw hapus yg mana🗿

Emang sampe berapa plugin ? Coba aja di akalin jadi 1 plugins nya, misal tool apa gitu, nnti jadi 1 kek vn , antispam antilink sama antiviewonce jadi 1

**Comment by ImYanXiao** [comment]
> > > > @Xnuvers007 Bantu Kurangin Fitur yg nggk digunain, biar bisa muncul code pairing
> > > 
> > > 
> > > lagi capek gw :V nanti deh
> > 
> > 
> > Gw bingung mo gw hapus yg mana🗿
> 
> Emang sampe berapa plugin ? Coba aja di akalin jadi 1 plugins nya, misal tool apa gitu, nnti jadi 1 kek vn , antispam antilink sama antiviewonce jadi 1

Sampe mau muncul pairing aja sihh, klo udah sampe muncul kan udah tuh

**Comment by ImYanXiao** [comment]
@Xnuvers007 Udh Fix PairingCodenya🗿👍

**Comment by ImYanXiao** [comment]
> kabarin bang klo uda jadi:v

Done gan🗿👍
