### ISSUE TITLE
cuy Qrnya kok ga bisa ? Di replit *error

### ISSUE THREAD

**Issue by denz-aja** [ImYanXiao/Elaina-MultiDevice#128]

**Comment by ImYanXiao** [comment]
@Xnuvers007 saran? 😂

**Comment by ImYanXiao** [comment]
> _No description provided._

Ada panel free klo ga salah di issues, coba aja run disitu, nnti disuruh masukin nomor doang gaperlu 2hp lgi

**Comment by Xnuvers007** [comment]
> @Xnuvers007 saran? 😂

:V ngakak

**Comment by Xnuvers007** [comment]
> _No description provided._

coba reinstall lagi ? terus ikutin update ini.

soalnya ada beberapa yang udah di fix sih

**Comment by ImYanXiao** [comment]
> > _No description provided._
> 
> coba reinstall lagi ? terus ikutin update ini.
> 
> soalnya ada beberapa yang udah di fix sih

Gw bingung nih milih qr atau pairingcode

**Comment by denz-aja** [comment]
bedanya Qr sama pairing apa?

**Comment by denz-aja** [comment]
> > > _No description provided._
> > 
> > 
> > coba reinstall lagi ? terus ikutin update ini.
> > soalnya ada beberapa yang udah di fix sih
> 
> Gw bingung nih milih qr atau pairingcode

yang pairing caranya gimana?. hmmm

**Comment by Xnuvers007** [comment]
> > > _No description provided._
> > 
> > 
> > coba reinstall lagi ? terus ikutin update ini.
> > soalnya ada beberapa yang udah di fix sih
> 
> Gw bingung nih milih qr atau pairingcode

buat backup aja, bikin folder baru backup_waQR nanti isinya yang QR, terus yang ini pairing

begitu sih, jadi dipisah. atau mau bikin repo baru ? punya gw masih QR wkwkwk sengaja, soalnya belom berani coba pairing, niatnya mo gw taro di repo gw, sebagai backup

**Comment by ImYanXiao** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > coba reinstall lagi ? terus ikutin update ini.
> > > soalnya ada beberapa yang udah di fix sih
> > 
> > 
> > Gw bingung nih milih qr atau pairingcode
> 
> yang pairing caranya gimana?. hmmm

Nnti pas di start disuruh masukin nomor nah pas udh masukin nnti dikasih kode trs masuk ke perangkat tertaut trs dibawah ada tulisan tautkan dengan nomor telepon saja trs ketik situ kodenya, dah kelar😁
