### ISSUE TITLE
Code pairing eror

### ISSUE THREAD

**Issue by AlisaOfc** [ImYanXiao/Elaina-MultiDevice#129]
![Screenshot_20230920_215445](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/122805772/2c099580-5168-4312-8329-e95840a79242)

Eror mastah 🗿 GK bisa connect udh kucoba otak atik sendiri tetapi hasil nya tetap nihil, udah kucoba minta bantuan sama bang Dika tetep GK bisa juga. moga ni issue di tanggepin :v

**Comment by ImYanXiao** [comment]
> ![Screenshot_20230920_215445](https://user-images.githubusercontent.com/122805772/269399498-2c099580-5168-4312-8329-e95840a79242.jpg)
> 
> Eror mastah 🗿 GK bisa connect udh kucoba otak atik sendiri tetapi hasil nya tetap nihil, udah kucoba minta bantuan sama bang Dika tetep GK bisa juga. moga ni issue di tanggepin :v

Bagian browser main.js di custom kah?

**Comment by AlisaOfc** [comment]
> > ![Screenshot_20230920_215445](https://user-images.githubusercontent.com/122805772/269399498-2c099580-5168-4312-8329-e95840a79242.jpg)
> > Eror mastah 🗿 GK bisa connect udh kucoba otak atik sendiri tetapi hasil nya tetap nihil, udah kucoba minta bantuan sama bang Dika tetep GK bisa juga. moga ni issue di tanggepin :v
> 
> Bagian browser main.js di custom kah?

kgk

**Comment by ImYanXiao** [comment]
> > > ![Screenshot_20230920_215445](https://user-images.githubusercontent.com/122805772/269399498-2c099580-5168-4312-8329-e95840a79242.jpg)
> > > Eror mastah 🗿 GK bisa connect udh kucoba otak atik sendiri tetapi hasil nya tetap nihil, udah kucoba minta bantuan sama bang Dika tetep GK bisa juga. moga ni issue di tanggepin :v
> > 
> > 
> > Bagian browser main.js di custom kah?
> 
> kgk

![Screenshot_2023-09-21-10-46-59-710_com gbwhatsapp](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/102222065/a9982280-f705-4987-9efb-272c46dd5b45)
Jir fek bat🗿

**Comment by AlisaOfc** [comment]
> Jir fek bat 🗿

yaudh gw coba ulang

**Comment by ImYanXiao** [comment]
> > Jir fek bat 🗿
> 
> yaudh gw coba ulang

Nodejs Brp? 18? 17? 19? 20?

**Comment by AlisaOfc** [comment]
> > > Jir fek bat 🗿
> > 
> > 
> > yaudh gw coba ulang
> 
> Nodejs Brp? 18? 17? 19? 20?

18 kalo GK salah gw lupa

**Comment by AlisaOfc** [comment]
> > > Jir fek bat 🗿
> > 
> > 
> > yaudh gw coba ulang
> 
> Nodejs Brp? 18? 17? 19? 20?

18 kalo GK salah gw lupa

**Comment by ImYanXiao** [comment]
> > > > Jir fek bat 🗿
> > > 
> > > 
> > > yaudh gw coba ulang
> > 
> > 
> > Nodejs Brp? 18? 17? 19? 20?
> 
> 18 kalo GK salah gw lupa

Cek sj, node -v, coba ubah baileysnya ke npm soalnya gw tdi pas mo nyoba gbisa install gegara nodejs yg gw pke buat tes 17 18🗿

**Comment by ImYanXiao** [comment]
> > > > > > Jir fek bat 🗿
> > > > > 
> > > > > 
> > > > > yaudh gw coba ulang
> > > > 
> > > > 
> > > > Nodejs Brp? 18? 17? 19? 20?
> > > 
> > > 
> > > 18 kalo GK salah gw lupa
> > 
> > 
> > Cek sj, node -v, coba ubah baileysnya ke npm soalnya gw tdi pas mo nyoba gbisa install gegara nodejs yg gw pke buat tes 17 18🗿
> 
> eh kok gw kek error trs ada kata kata kek "all"

Ah async all kan??

**Comment by denz-aja** [comment]
> > > > > > > Jir fek bat 🗿
> > > > > > 
> > > > > > 
> > > > > > yaudh gw coba ulang
> > > > > 
> > > > > 
> > > > > Nodejs Brp? 18? 17? 19? 20?
> > > > 
> > > > 
> > > > 18 kalo GK salah gw lupa
> > > 
> > > 
> > > Cek sj, node -v, coba ubah baileysnya ke npm soalnya gw tdi pas mo nyoba gbisa install gegara nodejs yg gw pke buat tes 17 18🗿
> > 
> > 
> > eh kok gw kek error trs ada kata kata kek "all"
> 
> Ah async all kan??

udah bisa

**Comment by ImYanXiao** [comment]
Gw Tutup, klo ada error re open atau bikin issues baru gpp
