### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sneznat** [ImYanXiao/Elaina-MultiDevice#130]
![Screenshot_2023-09-22-22-32-50-409_com android chrome-edit](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/110214957/8b2f9eee-96ab-4e90-972d-afcc07bdb454)
Kenapa ini bang? Bot nya jadi centang 1

**Comment by ImYanXiao** [comment]
Malas Menanggapi

https://github.com/npm/npm/issues/13806
