### ISSUE TITLE
? :v

### ISSUE THREAD

**Issue by ImYanXiao** [ImYanXiao/Elaina-MultiDevice#131]
@Xnuvers007 why diganti qr lagi?

**Comment by Xnuvers007** [comment]
> @Xnuvers007 why diganti qr lagi?

Hah ? Emang QR ? kagak diganti

**Comment by Xnuvers007** [comment]
:v gw gak ganti

**Comment by ImYanXiao** [comment]
> :v gw gak ganti

Bejirt bat, liat ae logs updatenya sblm w ganti :v

**Comment by Xnuvers007** [comment]
> Gw ada cara sih biar bisa pairing atau qr, ga ribet caranya cmn tinggal nambahin opts nanti yg di replit otomatis pke qr klo yg ngga di replit ya pke pairing

benerrr nih, gw tadi coba di replit pairing emang agak gimana.

**Comment by Xnuvers007** [comment]
> > :v gw gak ganti
> 
> Bejirt bat, liat ae logs updatenya sblm w ganti :v

tapi gw ngerasa gak ganti anjir sumpah :V emang logs mana ? file apa ?

**Comment by ImYanXiao** [comment]
> > > :v gw gak ganti
> > 
> > 
> > Bejirt bat, liat ae logs updatenya sblm w ganti :v
> 
> tapi gw ngerasa gak ganti anjir sumpah :V emang logs mana ? file apa ?

![Screenshot_2023-10-13-17-43-55-267_com android chrome](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/102222065/20d78b68-4aa5-4061-890a-585bebdd8da1)

Yg ini banh, liat aja yg main.js

**Comment by Xnuvers007** [comment]
> > > > :v gw gak ganti
> > > 
> > > 
> > > Bejirt bat, liat ae logs updatenya sblm w ganti :v
> > 
> > 
> > tapi gw ngerasa gak ganti anjir sumpah :V emang logs mana ? file apa ?
> 
> ![Screenshot_2023-10-13-17-43-55-267_com android chrome](https://user-images.githubusercontent.com/102222065/274878826-20d78b68-4aa5-4061-890a-585bebdd8da1.jpg)
> 
> Yg ini banh, liat aja yg main.js

lah iya :V, tapi gw tadi mo nambahin ini doank sih


```
 try {
	// Jika anda menggunakan replit, gunakan yang sevenHoursLater dan tambahkan // pada const Handler
	// Default: server/vps/panel, replit + 7 jam buat jam indonesia
        // const sevenHoursLater = Date.now() + 7 * 60 * 60 * 1000;
        const Handler = await import(`./handler.js?update=${Date.now()}`).catch(console.error)
      // const Handler = await import(`./handler.js?update=${sevenHoursLater}`).catch(console.error)
```

 
 
tapi gw tadi gak ada ngubah gitu, niatnya mo tambahin begitu untuk replit.

**Comment by ImYanXiao** [comment]
> > > > > :v gw gak ganti
> > > > 
> > > > 
> > > > Bejirt bat, liat ae logs updatenya sblm w ganti :v
> > > 
> > > 
> > > tapi gw ngerasa gak ganti anjir sumpah :V emang logs mana ? file apa ?
> > 
> > 
> > ![Screenshot_2023-10-13-17-43-55-267_com android chrome](https://user-images.githubusercontent.com/102222065/274878826-20d78b68-4aa5-4061-890a-585bebdd8da1.jpg)
> > Yg ini banh, liat aja yg main.js
> 
> lah iya :V, tapi gw tadi mo nambahin ini doank sih
> 
> ```
>  try {
> 	// Jika anda menggunakan replit, gunakan yang sevenHoursLater dan tambahkan // pada const Handler
> 	// Default: server/vps/panel, replit + 7 jam buat jam indonesia
>         // const sevenHoursLater = Date.now() + 7 * 60 * 60 * 1000;
>         const Handler = await import(`./handler.js?update=${Date.now()}`).catch(console.error)
>       // const Handler = await import(`./handler.js?update=${sevenHoursLater}`).catch(console.error)
> ```
> 
> tapi gw tadi gak ada ngubah gitu, niatnya mo tambahin begitu untuk replit.

Okok, tambahin lagi aja ngab bagian Date Timenya🐦

**Comment by abclimadasar** [comment]
> > > > > :v gw gak ganti
> > > > 
> > > > 
> > > > Bejirt bat, liat ae logs updatenya sblm w ganti :v
> > > 
> > > 
> > > tapi gw ngerasa gak ganti anjir sumpah :V emang logs mana ? file apa ?
> > 
> > 
> > ![Screenshot_2023-10-13-17-43-55-267_com android chrome](https://user-images.githubusercontent.com/102222065/274878826-20d78b68-4aa5-4061-890a-585bebdd8da1.jpg)
> > Yg ini banh, liat aja yg main.js
> 
> lah iya :V, tapi gw tadi mo nambahin ini doank sih
> 
> ```
>  try {
> 	// Jika anda menggunakan replit, gunakan yang sevenHoursLater dan tambahkan // pada const Handler
> 	// Default: server/vps/panel, replit + 7 jam buat jam indonesia
>         // const sevenHoursLater = Date.now() + 7 * 60 * 60 * 1000;
>         const Handler = await import(`./handler.js?update=${Date.now()}`).catch(console.error)
>       // const Handler = await import(`./handler.js?update=${sevenHoursLater}`).catch(console.error)
> ```
> 
> tapi gw tadi gak ada ngubah gitu, niatnya mo tambahin begitu untuk replit.

Itu buat apa puh

**Comment by Xnuvers007** [comment]
> > > > > > :v gw gak ganti
> > > > > 
> > > > > 
> > > > > Bejirt bat, liat ae logs updatenya sblm w ganti :v
> > > > 
> > > > 
> > > > tapi gw ngerasa gak ganti anjir sumpah :V emang logs mana ? file apa ?
> > > 
> > > 
> > > ![Screenshot_2023-10-13-17-43-55-267_com android chrome](https://user-images.githubusercontent.com/102222065/274878826-20d78b68-4aa5-4061-890a-585bebdd8da1.jpg)
> > > Yg ini banh, liat aja yg main.js
> > 
> > 
> > lah iya :V, tapi gw tadi mo nambahin ini doank sih
> > ```
> >  try {
> > 	// Jika anda menggunakan replit, gunakan yang sevenHoursLater dan tambahkan // pada const Handler
> > 	// Default: server/vps/panel, replit + 7 jam buat jam indonesia
> >         // const sevenHoursLater = Date.now() + 7 * 60 * 60 * 1000;
> >         const Handler = await import(`./handler.js?update=${Date.now()}`).catch(console.error)
> >       // const Handler = await import(`./handler.js?update=${sevenHoursLater}`).catch(console.error)
> > ```
> > 
> > 
> > tapi gw tadi gak ada ngubah gitu, niatnya mo tambahin begitu untuk replit.
> 
> Itu buat apa puh

Waktu puh🥺🙏
