### ISSUE TITLE
bang buat fitur daftar versi verifikasi pake email

### ISSUE THREAD

**Issue by waceera** [ImYanXiao/Elaina-MultiDevice#136]

**Comment by ImYanXiao** [comment]
> _No description provided._

Sangadlah malas pakai nodemailer

**Comment by waceera** [comment]
buat fitur jadibot 🗿

**Comment by Xnuvers007** [comment]
> buat fitur jadibot 🗿

yakin gak berat tuh server ? setauku ya, kalo jadi bot, semakin banyak orang, makin gede tuh database ditambah manajemen file download dari si user, mesti 1 menit per file wkwkwk

**Comment by waceera** [comment]
btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)

**Comment by waceera** [comment]
> btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)

(tapi fitur-fitur yg error gw samain sama yg terbaru)

**Comment by ShirokamiRyzen** [comment]
> btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)

ganti aja menunya pake yang versi baru

**Comment by waceera** [comment]
> > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> 
> ganti aja menunya pake yang versi baru

tetep aja bjir

**Comment by ShirokamiRyzen** [comment]
> > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > 
> > 
> > ganti aja menunya pake yang versi baru
> 
> tetep aja bjir

coba test menunya pake nomer botnya, muncul gk

**Comment by waceera** [comment]
bentar bersihin memori

**Comment by waceera** [comment]
> > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > 
> > > 
> > > ganti aja menunya pake yang versi baru
> > 
> > 
> > tetep aja bjir
> 
> coba test menunya pake nomer botnya, muncul gk

sama aja gabisa

**Comment by waceera** [comment]
pas di .gp menu gabisa juga

**Comment by waceera** [comment]
tapi ada file menunya di r3p1t

> > > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > > 
> > > > 
> > > > ganti aja menunya pake yang versi baru
> > > 
> > > 
> > > tetep aja bjir
> > 
> > 
> > coba test menunya pake nomer botnya, muncul gk
> 
> sama aja gabisa

tapi ada filenya

**Comment by ShirokamiRyzen** [comment]
> tapi ada file menunya di r3p1t
> 
> > > > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > > > 
> > > > > 
> > > > > ganti aja menunya pake yang versi baru
> > > > 
> > > > 
> > > > tetep aja bjir
> > > 
> > > 
> > > coba test menunya pake nomer botnya, muncul gk
> > 
> > 
> > sama aja gabisa

coba send link replitnya

**Comment by waceera** [comment]
> > tapi ada file menunya di r3p1t
> > > > > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > > > > 
> > > > > > 
> > > > > > ganti aja menunya pake yang versi baru
> > > > > 
> > > > > 
> > > > > tetep aja bjir
> > > > 
> > > > 
> > > > coba test menunya pake nomer botnya, muncul gk
> > > 
> > > 
> > > sama aja gabisa
> 
> coba send link replitnya

https://replit.com/@mizacantik123uw/Elaina-MultiDevice-Qr kalo ga ada bilang

**Comment by waceera** [comment]
> > > tapi ada file menunya di r3p1t
> > > > > > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > > > > > 
> > > > > > > 
> > > > > > > ganti aja menunya pake yang versi baru
> > > > > > 
> > > > > > 
> > > > > > tetep aja bjir
> > > > > 
> > > > > 
> > > > > coba test menunya pake nomer botnya, muncul gk
> > > > 
> > > > 
> > > > sama aja gabisa
> > 
> > 
> > coba send link replitnya
> 
> https://replit.com/@mizacantik123uw/Elaina-MultiDevice-Qr kalo ga ada bilang

(ini versi qr btw)

**Comment by ShirokamiRyzen** [comment]
> > > > tapi ada file menunya di r3p1t
> > > > > > > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ganti aja menunya pake yang versi baru
> > > > > > > 
> > > > > > > 
> > > > > > > tetep aja bjir
> > > > > > 
> > > > > > 
> > > > > > coba test menunya pake nomer botnya, muncul gk
> > > > > 
> > > > > 
> > > > > sama aja gabisa
> > > 
> > > 
> > > coba send link replitnya
> > 
> > 
> > https://replit.com/@mizacantik123uw/Elaina-MultiDevice-Qr kalo ga ada bilang
> 
> (ini versi qr btw)

databasenya coba kosongin atau rename

**Comment by waceera** [comment]
> > > > > tapi ada file menunya di r3p1t
> > > > > > > > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ganti aja menunya pake yang versi baru
> > > > > > > > 
> > > > > > > > 
> > > > > > > > tetep aja bjir
> > > > > > > 
> > > > > > > 
> > > > > > > coba test menunya pake nomer botnya, muncul gk
> > > > > > 
> > > > > > 
> > > > > > sama aja gabisa
> > > > 
> > > > 
> > > > coba send link replitnya
> > > 
> > > 
> > > https://replit.com/@mizacantik123uw/Elaina-MultiDevice-Qr kalo ga ada bilang
> > 
> > 
> > (ini versi qr btw)
> 
> databasenya coba kosongin atau rename

database.json

**Comment by waceera** [comment]
> > > > > > tapi ada file menunya di r3p1t
> > > > > > > > > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ganti aja menunya pake yang versi baru
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > tetep aja bjir
> > > > > > > > 
> > > > > > > > 
> > > > > > > > coba test menunya pake nomer botnya, muncul gk
> > > > > > > 
> > > > > > > 
> > > > > > > sama aja gabisa
> > > > > 
> > > > > 
> > > > > coba send link replitnya
> > > > 
> > > > 
> > > > https://replit.com/@mizacantik123uw/Elaina-MultiDevice-Qr kalo ga ada bilang
> > > 
> > > 
> > > (ini versi qr btw)
> > 
> > 
> > databasenya coba kosongin atau rename
> 
> database.json

pas mau kosongin loading mulu

**Comment by waceera** [comment]
> > > > > > > tapi ada file menunya di r3p1t
> > > > > > > > > > > > btw menu bot di gw kok ga muncul ya? (btw gw masih pake sc elaina versi lama)
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > ganti aja menunya pake yang versi baru
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > tetep aja bjir
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > coba test menunya pake nomer botnya, muncul gk
> > > > > > > > 
> > > > > > > > 
> > > > > > > > sama aja gabisa
> > > > > > 
> > > > > > 
> > > > > > coba send link replitnya
> > > > > 
> > > > > 
> > > > > https://replit.com/@mizacantik123uw/Elaina-MultiDevice-Qr kalo ga ada bilang
> > > > 
> > > > 
> > > > (ini versi qr btw)
> > > 
> > > 
> > > databasenya coba kosongin atau rename
> > 
> > 
> > database.json
> 
> pas mau kosongin loading mulu

dah ku rename

**Comment by ShirokamiRyzen** [comment]
kondisi database kosong terus restart ketik .menu

**Comment by waceera** [comment]
ebuset dah

**Comment by waceera** [comment]
banyak user

**Comment by ShirokamiRyzen** [comment]
database lu berantakan sih jadi gw suruh test botnya tanpa database, kalo menunya normal berarti database lu bermasalah

**Comment by waceera** [comment]
> database lu berantakan sih jadi gw suruh test botnya tanpa database, kalo menunya normal berarti database lu bermasalah

bisa jadi sih

**Comment by waceera** [comment]
apa hapus aja file databasenya?

**Comment by ShirokamiRyzen** [comment]
bebas sih, kalo gada isi yang penting hapus aja

**Comment by waceera** [comment]
pas hapus, LAHIR LAGI

**Comment by waceera** [comment]
PAS MW START, LAMA BNGT

**Comment by waceera** [comment]
> PAS MW START, LAMA BNGT

(sory, lupa matiin caps lock)

**Comment by ShirokamiRyzen** [comment]
> pas hapus, LAHIR LAGI

iya ga masalah, yang penting databasenya fresh

**Comment by ShirokamiRyzen** [comment]
> PAS MW START, LAMA BNGT

ganti pake panel aja

**Comment by waceera** [comment]
> > PAS MW START, LAMA BNGT
> 
> ganti pake panel aja

oh sory, gw orang nya gratisan

**Comment by ShirokamiRyzen** [comment]
> > > PAS MW START, LAMA BNGT
> > 
> > 
> > ganti pake panel aja
> 
> oh sory, gw orang nya gratisan

#79

**Comment by waceera** [comment]
> > > > PAS MW START, LAMA BNGT
> > > 
> > > 
> > > ganti pake panel aja
> > 
> > 
> > oh sory, gw orang nya gratisan
> 
> cek di #79

yey panel gratis

**Comment by waceera** [comment]
> > > > > PAS MW START, LAMA BNGT
> > > > 
> > > > 
> > > > ganti pake panel aja
> > > 
> > > 
> > > oh sory, gw orang nya gratisan
> > 
> > 
> > cek di #79
> 
> yey panel gratis

udah

**Comment by waceera** [comment]
> > > > PAS MW START, LAMA BNGT
> > > 
> > > 
> > > ganti pake panel aja
> > 
> > 
> > oh sory, gw orang nya gratisan
> 
> cek di #79

File Elaina-MultiDevice-Qr.zip is larger than the maximum file upload size of 100 MB. @ShirokamiRyzen

**Comment by ShirokamiRyzen** [comment]
gausah di upload sama node_modules nya juga dong -_-

**Comment by waceera** [comment]
gabisa dipisahin jir node_modulesnya

**Comment by waceera** [comment]
issue ini saya tutup, thanks.
