### ISSUE TITLE
Bang buat fitur jadibot ver pairing 

### ISSUE THREAD

**Issue by Justpannstore** [ImYanXiao/Elaina-MultiDevice#138]
Bantu gw

**Comment by Justpannstore** [comment]
@ImYanXiao

**Comment by Justpannstore** [comment]
Atau cpanel aja

**Comment by ImYanXiao** [comment]
> @ImYanXiao

🗿?

**Comment by ImYanXiao** [comment]
Next, soalnya klo bikin jadibot pke pairing ga iso nnti di terminal terputus bot lu soalnya kek bikin sesi baru lagi di terminal
