### ISSUE TITLE
Report #2

### ISSUE THREAD

**Issue by waceera** [ImYanXiao/Elaina-MultiDevice#139]
min, kok di gw owner-sf nya rusak? btw error nya erofs

**Comment by waceera** [comment]
Error: EROFS: read-only file system gitu bg errornya

**Comment by ShirokamiRyzen** [comment]
Perhatikan directorynya, itu ente nyimpen ke root folder/container panelnya

**Comment by waceera** [comment]
> Perhatikan directorynya, itu ente nyimpen ke root folder/container panelnya

aing masih pake replit neng

**Comment by waceera** [comment]
tadi command nya .sf plugins/apalah.js

**Comment by ShirokamiRyzen** [comment]
Pake relative directory

E.g:
`./script.js` / `../plugins/script.js`

Kalo masih gabisa set folder plugins ke 775 (itu folder lu read only)

**Comment by waceera** [comment]
bang, pas gw buka folder src sama session, pas buka "FileSystemUnavailable" gw baru liat error ini. 

> Pake relative directory
> 
> E.g: `./script.js` / `../plugins/script.js`
> 
> Kalo masih gabisa set folder plugins ke 775 (itu folder lu read only)

**Comment by Xnuvers007** [comment]
> Error: EROFS: read-only file system gitu bg errornya

read only, berarti kemungkinan folder plugins itu masih akses baca doank (read only) coba bikin 777 atau 775

`chmod -Rf 755 plugins/`
