### ISSUE TITLE
INFOKAN APIKEY

### ISSUE THREAD

**Issue by irhanftelis** [ImYanXiao/Elaina-MultiDevice#141]
om bagi apikey hehehe:(

**Comment by Xnuvers007** [comment]
> om bagi apikey hehehe:(

API key apaan ? sebenernya sih enakan bot kalo dibuat pure code, bukan dari APIKEY, nanti kalo suatu saat bakal mati si Server penyedia layanan APIKEY gimane ? :) kayak xzn.wtf terus xteam, dll. huh

**Comment by irhanftelis** [comment]
om tiktok downloader kok error ya?

**Comment by Xnuvers007** [comment]
> om tiktok downloader kok error ya?

error gimana ? kasih tau.
kalo error gabisa download tiktok video, berarti dari server untuk download tiktok tersebut gak support buat download videonya, mau gak mau user download sendiri, gw sendiri juga lagi bingung buatnya. jangan salahkan di botnya tapi salah di server (https://tikdown.org)

**Comment by ShirokamiRyzen** [comment]
> om tiktok downloader kok error ya?

coba pake yang gw [disini](https://github.com/ShirokamiRyzen/Nao-MD/blob/main/plugins/downloader-tiktok.js)

**Comment by Xnuvers007** [comment]
> om tiktok downloader kok error ya?

Done ya
