### ISSUE TITLE
reques allfake lihat saluran 😁

### ISSUE THREAD

**Issue by waceera** [ImYanXiao/Elaina-MultiDevice#143]

**Comment by ImYanXiao** [comment]
Ezet

**Comment by sneznat** [comment]
> Ezet

![IMG_20231217_151856](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/110214957/41245f67-a831-4b5b-b669-7b84aadf373c)
Nih gak bisa di rename ya "Lihat saluran" nya?

**Comment by waceera** [comment]
> Ezet



> > Ezet
> 
> ![IMG_20231217_151856](https://private-user-images.githubusercontent.com/110214957/291049386-41245f67-a831-4b5b-b669-7b84aadf373c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODE5MjgsIm5iZiI6MTcwMjg4MTYyOCwicGF0aCI6Ii8xMTAyMTQ5NTcvMjkxMDQ5Mzg2LTQxMjQ1ZjY3LWE4MzEtNGI1Yi1iNjY5LTdiODRhYWRmMzczYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNjQwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTljMTc4YjY1NmVmY2JlODkxYWQ4YjJhMzUxZmE5ZDNhYjBhNDE4OTVhNmI4NDQ3ZjRkMGJmODg4MTMzZDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XvzwQZuJf5B7cvk05EltBi08PHD_a03KHhOSlakaX6I) Nih gak bisa di rename ya "Lihat saluran" nya?

waduh bang boleh minta plugin allfake nya bang?

**Comment by sneznat** [comment]
> > Ezet
> 
> > > Ezet
> > 
> > 
> > ![IMG_20231217_151856](https://private-user-images.githubusercontent.com/110214957/291049386-41245f67-a831-4b5b-b669-7b84aadf373c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODE5MjgsIm5iZiI6MTcwMjg4MTYyOCwicGF0aCI6Ii8xMTAyMTQ5NTcvMjkxMDQ5Mzg2LTQxMjQ1ZjY3LWE4MzEtNGI1Yi1iNjY5LTdiODRhYWRmMzczYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNjQwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTljMTc4YjY1NmVmY2JlODkxYWQ4YjJhMzUxZmE5ZDNhYjBhNDE4OTVhNmI4NDQ3ZjRkMGJmODg4MTMzZDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XvzwQZuJf5B7cvk05EltBi08PHD_a03KHhOSlakaX6I) Nih gak bisa di rename ya "Lihat saluran" nya?
> 
> waduh bang boleh minta plugin allfake nya bang?

Gimana ngirim nya? :V

**Comment by ImYanXiao** [comment]
Gw mo kasih caranya tp bingung soalnya adreplynya nnti hilang, tp klo mo adreplynya ga hilang isi aja global.adReplynya bagian sourceUrl pke url channel

**Comment by waceera** [comment]
> > > Ezet
> > 
> > 
> > > > Ezet
> > > 
> > > 
> > > ![IMG_20231217_151856](https://private-user-images.githubusercontent.com/110214957/291049386-41245f67-a831-4b5b-b669-7b84aadf373c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODE5MjgsIm5iZiI6MTcwMjg4MTYyOCwicGF0aCI6Ii8xMTAyMTQ5NTcvMjkxMDQ5Mzg2LTQxMjQ1ZjY3LWE4MzEtNGI1Yi1iNjY5LTdiODRhYWRmMzczYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNjQwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTljMTc4YjY1NmVmY2JlODkxYWQ4YjJhMzUxZmE5ZDNhYjBhNDE4OTVhNmI4NDQ3ZjRkMGJmODg4MTMzZDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XvzwQZuJf5B7cvk05EltBi08PHD_a03KHhOSlakaX6I) Nih gak bisa di rename ya "Lihat saluran" nya?
> > 
> > 
> > waduh bang boleh minta plugin allfake nya bang?
> 
> Gimana ngirim nya? :V

ke wa :v
