### ISSUE TITLE
Maybe Bug atau perlu Penyesuaian

### ISSUE THREAD

**Issue by RFIunknown** [ImYanXiao/Elaina-MultiDevice#144]
Pairing code pas udah masukin nomer malah Reviced ga langsung dikirim code nya, perlu di spam dulu baru code nya dikirim

**Comment by Xnuvers007** [comment]
> Pairing code pas udah masukin nomer malah Reviced ga langsung dikirim code nya, perlu di spam dulu baru code nya dikirim

kayaknya itu dari baileysnya deh

**Comment by ImYanXiao** [comment]
> Pairing code pas udah masukin nomer malah Reviced ga langsung dikirim code nya, perlu di spam dulu baru code nya dikirim

Kok di gw pas baru input nomer langsung dikasih kode ya

**Comment by waceera** [comment]
> > Pairing code pas udah masukin nomer malah Reviced ga langsung dikirim code nya, perlu di spam dulu baru code nya dikirim
> 
> Kok di gw pas baru input nomer langsung dikasih kode ya

gw direplit juga gitu bang, pairing code pas reviced ga dikirim code nya.

**Comment by ImYanXiao** [comment]
> > > Pairing code pas udah masukin nomer malah Reviced ga langsung dikirim code nya, perlu di spam dulu baru code nya dikirim
> > 
> > 
> > Kok di gw pas baru input nomer langsung dikasih kode ya
> 
> gw direplit juga gitu bang, pairing code pas reviced ga dikirim code nya.

Semenjak pairing blm nyoba lagi di replit🗿
