### ISSUE TITLE
apikey yg berkaitan tr.deployers.repl.co error semua woilah

### ISSUE THREAD

**Issue by waceera** [ImYanXiao/Elaina-MultiDevice#148]
ini disebabkan karena pembaruan replit 🗿🙏

**Comment by ImYanXiao** [comment]
> ini disebabkan karena pembaruan replit 🗿🙏
🗿

**Comment by Xnuvers007** [comment]
> ini disebabkan karena pembaruan replit 🗿🙏

ganti ke link ini bang https://0e87ad76-6c4e-40ff-bb5a-6bbdab145ae2-00-39qk1kw7vab6l.worf.replit.dev/

**Comment by Xnuvers007** [comment]
gw bingung mau deploy ke mana hadehhh ke vercel juga masih males aku huhh, bantu donk 🗿

**Comment by Xnuvers007** [comment]
> > ini disebabkan karena pembaruan replit 🗿🙏
> 
> ganti ke link ini bang https://0e87ad76-6c4e-40ff-bb5a-6bbdab145ae2-00-39qk1kw7vab6l.worf.replit.dev/

@ImYanXiao @waceera

**Comment by ImYanXiao** [comment]
> > > ini disebabkan karena pembaruan replit 🗿🙏
> > 
> > 
> > ganti ke link ini bang https://0e87ad76-6c4e-40ff-bb5a-6bbdab145ae2-00-39qk1kw7vab6l.worf.replit.dev/
> 
> @ImYanXiao @waceera

Awikwok kami pergi

**Comment by waceera** [comment]
> > > ini disebabkan karena pembaruan replit 🗿🙏
> > 
> > 
> > ganti ke link ini bang https://0e87ad76-6c4e-40ff-bb5a-6bbdab145ae2-00-39qk1kw7vab6l.worf.replit.dev/
> 
> @ImYanXiao @waceera

tutor 24 jam woilah

**Comment by waceera** [comment]
> > > ini disebabkan karena pembaruan replit 🗿🙏
> > 
> > 
> > ganti ke link ini bang https://0e87ad76-6c4e-40ff-bb5a-6bbdab145ae2-00-39qk1kw7vab6l.worf.replit.dev/
> 
> @ImYanXiao @waceera

The Repl is currently not running.

**Comment by ShirokamiRyzen** [comment]
> gw bingung mau deploy ke mana hadehhh ke vercel juga masih males aku huhh, bantu donk 🗿

deploy ke [DBH](https://github.com/DanBot-Hosting)
