### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by diki6969** [ImYanXiao/Elaina-MultiDevice#150]
perbarui readme nyaa biar enak

**Comment by Xnuvers007** [comment]
> perbarui readme nyaa biar enak

apanya yang mau di perbarui ?

**Comment by ImYanXiao** [comment]
> perbarui readme nyaa biar enak

Gw yg males update krn dijual beliin😂

**Comment by diki6969** [comment]
> > perbarui readme nyaa biar enak
> 
> apanya yang mau di perbarui ?

kan banyak perubahan di sc nya kek pairing atau apapun itu

di readme juga ditambahin
