### ISSUE TITLE
Error: Connection Closed

### ISSUE THREAD

**Issue by sosokhitam6** [ImYanXiao/Elaina-MultiDevice#153]
Setalah aku input nomor buat pairing kode selalu error gini bang
![Screenshot_20240217-075217_JuiceSSH](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/160292496/06bd5d75-8f4c-4c17-94e9-35fb53b60e3f)

**Comment by ImYanXiao** [comment]
> Setalah aku input nomor buat pairing kode selalu error gini bang ![Screenshot_20240217-075217_JuiceSSH](https://private-user-images.githubusercontent.com/160292496/305586947-06bd5d75-8f4c-4c17-94e9-35fb53b60e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzM1MjgsIm5iZiI6MTcwODE3MzIyOCwicGF0aCI6Ii8xNjAyOTI0OTYvMzA1NTg2OTQ3LTA2YmQ1ZDc1LThmNGMtNGMxNy05NGU5LTM1ZmI1M2I2MGUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxMjMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmQ3NTZjN2ZkOTkwNDgwOWNiZWQwYzg1YTRkNGIwZjU2ZDFkY2NhYmUwYjBjYzBhNzg5NDU1ODZmOWU5ZDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Qkdm5d23PNU5gPSYMVps0-ccnLAFjAlbbbFqQzn6-c)

Ada file sesi sblmny ketika di input bentrok

**Comment by Xnuvers007** [comment]
> > Setalah aku input nomor buat pairing kode selalu error gini bang ![Screenshot_20240217-075217_JuiceSSH](https://private-user-images.githubusercontent.com/160292496/305586947-06bd5d75-8f4c-4c17-94e9-35fb53b60e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzM1MjgsIm5iZiI6MTcwODE3MzIyOCwicGF0aCI6Ii8xNjAyOTI0OTYvMzA1NTg2OTQ3LTA2YmQ1ZDc1LThmNGMtNGMxNy05NGU5LTM1ZmI1M2I2MGUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxMjMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmQ3NTZjN2ZkOTkwNDgwOWNiZWQwYzg1YTRkNGIwZjU2ZDFkY2NhYmUwYjBjYzBhNzg5NDU1ODZmOWU5ZDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Qkdm5d23PNU5gPSYMVps0-ccnLAFjAlbbbFqQzn6-c)
> 
> Ada file sesi sblmny ketika di input bentrok

Bro, bantu perbaiki fitur convertcode 🗿gw lagi blom bisa fix atau apapun itu

**Comment by ImYanXiao** [comment]
> > > Setalah aku input nomor buat pairing kode selalu error gini bang ![Screenshot_20240217-075217_JuiceSSH](https://private-user-images.githubusercontent.com/160292496/305586947-06bd5d75-8f4c-4c17-94e9-35fb53b60e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzM1MjgsIm5iZiI6MTcwODE3MzIyOCwicGF0aCI6Ii8xNjAyOTI0OTYvMzA1NTg2OTQ3LTA2YmQ1ZDc1LThmNGMtNGMxNy05NGU5LTM1ZmI1M2I2MGUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxMjMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmQ3NTZjN2ZkOTkwNDgwOWNiZWQwYzg1YTRkNGIwZjU2ZDFkY2NhYmUwYjBjYzBhNzg5NDU1ODZmOWU5ZDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Qkdm5d23PNU5gPSYMVps0-ccnLAFjAlbbbFqQzn6-c)
> > 
> > 
> > Ada file sesi sblmny ketika di input bentrok
> 
> Bro, bantu perbaiki fitur convertcode 🗿gw lagi blom bisa fix atau apapun itu
> 
> @ImYanXiao

Yg mana
