### ISSUE TITLE
Pairing code error?

### ISSUE THREAD

**Issue by sneznat** [ImYanXiao/Elaina-MultiDevice#155]
![Screenshot_2024-02-21-09-50-13-113_com whatsapp](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/110214957/2bd6848f-63cc-4dd0-bc4c-3f94c534aa17)
Ini kenapa bang kok error pas masukin kode?

**Comment by JER-OFC** [comment]
> ![Screenshot_2024-02-21-09-50-13-113_com whatsapp](https://private-user-images.githubusercontent.com/110214957/306478238-2bd6848f-63cc-4dd0-bc4c-3f94c534aa17.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjczNzYsIm5iZiI6MTcwODUyNzA3NiwicGF0aCI6Ii8xMTAyMTQ5NTcvMzA2NDc4MjM4LTJiZDY4NDhmLTYzY2MtNGRkMC1iYzRjLTNmOTRjNTM0YWExNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxNDUxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDNiOGMxZmNkYTY4MWM4ZjFmNmM2OTg0N2YyYmM2YTQ5NDczNDIwYjhmNjVhZTc2NmQyODRmOWM3MzIyMGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GxQPX42O0da6Kye0DDblDjHcnHLa2NpILc_oRbiwZoE) Ini kenapa bang kok error pas masukin kode?

Hapus semua pesan dlu sebelum pairing

Totorial jika blm tau 👇
> Pengaturan > chat > history chat > clear all chat

**Comment by sneznat** [comment]
> > ![Screenshot_2024-02-21-09-50-13-113_com whatsapp](https://private-user-images.githubusercontent.com/110214957/306478238-2bd6848f-63cc-4dd0-bc4c-3f94c534aa17.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjczNzYsIm5iZiI6MTcwODUyNzA3NiwicGF0aCI6Ii8xMTAyMTQ5NTcvMzA2NDc4MjM4LTJiZDY4NDhmLTYzY2MtNGRkMC1iYzRjLTNmOTRjNTM0YWExNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxNDUxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDNiOGMxZmNkYTY4MWM4ZjFmNmM2OTg0N2YyYmM2YTQ5NDczNDIwYjhmNjVhZTc2NmQyODRmOWM3MzIyMGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GxQPX42O0da6Kye0DDblDjHcnHLa2NpILc_oRbiwZoE) Ini kenapa bang kok error pas masukin kode?
> 
> Hapus semua pesan dlu sebelum pairing
> 
> Totorial jika blm tau 👇
> 
> > Pengaturan > chat > history chat > clear all chat

Gimana cara hapus pesannya kalau chat masih kosong? Padahal itu nomor baru daftar

**Comment by ImYanXiao** [comment]
> > > ![Screenshot_2024-02-21-09-50-13-113_com whatsapp](https://private-user-images.githubusercontent.com/110214957/306478238-2bd6848f-63cc-4dd0-bc4c-3f94c534aa17.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjczNzYsIm5iZiI6MTcwODUyNzA3NiwicGF0aCI6Ii8xMTAyMTQ5NTcvMzA2NDc4MjM4LTJiZDY4NDhmLTYzY2MtNGRkMC1iYzRjLTNmOTRjNTM0YWExNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxNDUxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDNiOGMxZmNkYTY4MWM4ZjFmNmM2OTg0N2YyYmM2YTQ5NDczNDIwYjhmNjVhZTc2NmQyODRmOWM3MzIyMGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GxQPX42O0da6Kye0DDblDjHcnHLa2NpILc_oRbiwZoE) Ini kenapa bang kok error pas masukin kode?
> > 
> > 
> > Hapus semua pesan dlu sebelum pairing
> > Totorial jika blm tau 👇
> > > Pengaturan > chat > history chat > clear all chat
> 
> Gimana cara hapus pesannya kalau chat masih kosong? Padahal itu nomor baru daftar

Bentar oe coba dulu

**Comment by ImYanXiao** [comment]
> ![Screenshot_2024-02-21-09-50-13-113_com whatsapp](https://private-user-images.githubusercontent.com/110214957/306478238-2bd6848f-63cc-4dd0-bc4c-3f94c534aa17.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjQxODEsIm5iZiI6MTcwODYyMzg4MSwicGF0aCI6Ii8xMTAyMTQ5NTcvMzA2NDc4MjM4LTJiZDY4NDhmLTYzY2MtNGRkMC1iYzRjLTNmOTRjNTM0YWExNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxNzQ0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmU2MTk5ZmI5NzJjOTdlNjFmZWMyODk4N2JmNzQwMDI4NGM0MDFkNGQ3YTBjYzM1OTcyOGRjMmVmZGY5YzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TYukiUjAhTo49zrYMIAby4OoqdsWdKLzpAzft6LgZPU) Ini kenapa bang kok error pas masukin kode?

![IMG_20240223_005505](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/102222065/83c7e5c7-7db8-43c2-86f4-800d4bc873fb)
 Bisa Connect Ini, coba cek lagi udh bener blum input nomornya?

**Comment by ImYanXiao** [comment]
> > > ![Screenshot_2024-02-21-09-50-13-113_com whatsapp](https://private-user-images.githubusercontent.com/110214957/306478238-2bd6848f-63cc-4dd0-bc4c-3f94c534aa17.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjQxODEsIm5iZiI6MTcwODYyMzg4MSwicGF0aCI6Ii8xMTAyMTQ5NTcvMzA2NDc4MjM4LTJiZDY4NDhmLTYzY2MtNGRkMC1iYzRjLTNmOTRjNTM0YWExNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxNzQ0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmU2MTk5ZmI5NzJjOTdlNjFmZWMyODk4N2JmNzQwMDI4NGM0MDFkNGQ3YTBjYzM1OTcyOGRjMmVmZGY5YzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TYukiUjAhTo49zrYMIAby4OoqdsWdKLzpAzft6LgZPU) Ini kenapa bang kok error pas masukin kode?
> > 
> > 
> > ![IMG_20240223_005505](https://private-user-images.githubusercontent.com/102222065/307098387-83c7e5c7-7db8-43c2-86f4-800d4bc873fb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDE3OTgsIm5iZiI6MTcwODc0MTQ5OCwicGF0aCI6Ii8xMDIyMjIwNjUvMzA3MDk4Mzg3LTgzYzdlNWM3LTdkYjgtNDNjMi04NmY0LTgwMGQ0YmM4NzNmYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMjI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTg4ZjQyOTUzZjIzYjVhMmQ5NzRmMDk3YTJlOTgwMDMwYmNiNjYxYTQyYmMwNjQxZTNhZjFiNDM2NGIxMzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IxJaBDdVxiG4THtOWv3vlnj-A-s4xyYi7A2Fze0jtE4) Bisa Connect Ini, coba cek lagi udh bener blum input nomornya?
> 
> ![Screenshot_2024-02-24-09-24-26-553_com deydaniki](https://private-user-images.githubusercontent.com/110214957/307488464-1af84c0d-3472-4e22-8045-43e4d1cd8eaa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTUwMjksIm5iZiI6MTcwOTAxNDcyOSwicGF0aCI6Ii8xMTAyMTQ5NTcvMzA3NDg4NDY0LTFhZjg0YzBkLTM0NzItNGUyMi04MDQ1LTQzZTRkMWNkOGVhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwNjE4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTk1N2YzYTQ4MzEzZjVjZDA2ZWZiYTQ3MDQ4YjY4YzI5NDMyNmU4NjM4MWEyOGZiODMyZWIzNTI1OGViYWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WsrC25bjCgVVBKCG76VBCVqZ9RC4pDj-R0K5GD-EklE) Nomor udah bener padahal soalnya langsung copas, tapi tetep aja gak bisa di pairing

Sorry telat telat balasnya, 3 kemungkinan antara nomornya atau codenya yg salah input atau versi whatsapp yg dipakai

**Comment by sneznat** [comment]
Sudah
