### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by KiyoEditz** [ImYanXiao/Elaina-MultiDevice#156]
Bang bisa bantu fix bot saya gak, masalah wm atau credits bisa di urus.

**Comment by ImYanXiao** [comment]
> Bang bisa bantu fix bot saya gak, masalah wm atau credits bisa di urus.

Knp tuh kira"

**Comment by KiyoEditz** [comment]
Ya ada lah masalah nya, bot nya konek tapi pas di .menu gak bisa

**Comment by ImYanXiao** [comment]
> Ya ada lah masalah nya, bot nya konek tapi pas di .menu gak bisa

Emang gabisa pke button sama list message, itu penyebabnya ga muncul menu

**Comment by KiyoEditz** [comment]
> > Ya ada lah masalah nya, bot nya konek tapi pas di .menu gak bisa
> 
> Emang gabisa pke button sama list message, itu penyebabnya ga muncul menu

Bisa bantu fix gak bang, coba di deploy dulu, nanti kalok ke fix saya kasih tqto

**Comment by ShirokamiRyzen** [comment]
> > > Ya ada lah masalah nya, bot nya konek tapi pas di .menu gak bisa
> > 
> > 
> > Emang gabisa pke button sama list message, itu penyebabnya ga muncul menu
> 
> Bisa bantu fix gak bang, coba di deploy dulu, nanti kalok ke fix saya kasih tqto

Ya itu udah dikasih tau, button sama list message udah gabisa, tu fitur udah dihapus sama wa dari 2022

**Comment by KiyoEditz** [comment]
> > > > Ya ada lah masalah nya, bot nya konek tapi pas di .menu gak bisa
> > > 
> > > 
> > > Emang gabisa pke button sama list message, itu penyebabnya ga muncul menu
> > 
> > 
> > Bisa bantu fix gak bang, coba di deploy dulu, nanti kalok ke fix saya kasih tqto
> 
> Ya itu udah dikasih tau, button sama list message udah gabisa, tu fitur udah dihapus sama wa dari 2022

Bot saya kalok di ketik menu ada muncul eror di bagian handler, simple, sama print nya, cuman pas di cek gak ada yang salah, bukan masalah button nya sama list

**Comment by ImYanXiao** [comment]
> > > > > Ya ada lah masalah nya, bot nya konek tapi pas di .menu gak bisa
> > > > 
> > > > 
> > > > Emang gabisa pke button sama list message, itu penyebabnya ga muncul menu
> > > 
> > > 
> > > Bisa bantu fix gak bang, coba di deploy dulu, nanti kalok ke fix saya kasih tqto
> > 
> > 
> > Ya itu udah dikasih tau, button sama list message udah gabisa, tu fitur udah dihapus sama wa dari 2022
> 
> Bot saya kalok di ketik menu ada muncul eror di bagian handler, simple, sama print nya, cuman pas di cek gak ada yang salah, bukan masalah button nya sama list

Ss

**Comment by ShirokamiRyzen** [comment]
> > > > > Ya ada lah masalah nya, bot nya konek tapi pas di .menu gak bisa
> > > > 
> > > > 
> > > > Emang gabisa pke button sama list message, itu penyebabnya ga muncul menu
> > > 
> > > 
> > > Bisa bantu fix gak bang, coba di deploy dulu, nanti kalok ke fix saya kasih tqto
> > 
> > 
> > Ya itu udah dikasih tau, button sama list message udah gabisa, tu fitur udah dihapus sama wa dari 2022
> 
> Bot saya kalok di ketik menu ada muncul eror di bagian handler, simple, sama print nya, cuman pas di cek gak ada yang salah, bukan masalah button nya sama list

ss

**Comment by KiyoEditz** [comment]
> > > > > > Ya ada lah masalah nya, bot nya konek tapi pas di .menu gak bisa
> > > > > 
> > > > > 
> > > > > Emang gabisa pke button sama list message, itu penyebabnya ga muncul menu
> > > > 
> > > > 
> > > > Bisa bantu fix gak bang, coba di deploy dulu, nanti kalok ke fix saya kasih tqto
> > > 
> > > 
> > > Ya itu udah dikasih tau, button sama list message udah gabisa, tu fitur udah dihapus sama wa dari 2022
> > 
> > Bot saya kalok di ketik menu ada muncul eror di bagian handler, simple, sama print nya, cuman pas di cek gak ada yang salah, bukan masalah button nya sama list
> 
> ss

Udah kelar bang, kebetulan Nemu owner bot yang mau bantu fix code nya, terima bang dah mau respon
