### ISSUE TITLE
Bang

### ISSUE THREAD

**Issue by irhanftelis** [ImYanXiao/Elaina-MultiDevice#157]
![Screenshot_20240311_172436](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/63201597/28d37713-1e24-4f92-9b5c-69e81b282700)

bangg ini gimana baru mau install tapi ginii mulu, di pannel gratisan optiklink

**Comment by ImYanXiao** [comment]
Slh install, kurang modulenya🗿

**Comment by irhanftelis** [comment]
gatau om biasanya klik start langsung ke run ke install semuaa tapi ini kaga😓

**Comment by Xnuvers007** [comment]
> Slh install, kurang modulenya🗿

Xiao, bantu fix web2mp4 atau fitur toimg, itu gabisa, dari website ezgif.com nya

**Comment by ShirokamiRyzen** [comment]
> > Slh install, kurang modulenya🗿
> 
> Xiao, bantu fix web2mp4 atau fitur toimg, itu gabisa, dari website ezgif.com nya @ImYanXiao

[#158](https://github.com/ImYanXiao/Elaina-MultiDevice/pull/158)

Gw bantu sticker toimg

**Comment by ImYanXiao** [comment]
> gatau om biasanya klik start langsung ke run ke install semuaa tapi ini kaga😓

Ganti versi baileys ke npm, soalnya klo versi github berat

**Comment by ImYanXiao** [comment]
> > Slh install, kurang modulenya🗿
> 
> Xiao, bantu fix web2mp4 atau fitur toimg, itu gabisa, dari website ezgif.com nya @ImYanXiao

Waduh 🗿

**Comment by irhanftelis** [comment]
> > gatau om biasanya klik start langsung ke run ke install semuaa tapi ini kaga😓
> 
> Ganti versi baileys ke npm, soalnya klo versi github berat

caranya gimana itu om, ga ngerti Hehe

**Comment by ImYanXiao** [comment]
> > > gatau om biasanya klik start langsung ke run ke install semuaa tapi ini kaga😓
> > 
> > 
> > Ganti versi baileys ke npm, soalnya klo versi github berat
> 
> caranya gimana itu om, ga ngerti Hehe

Udah kuganti tuh, tinggal copy

**Comment by Xnuvers007** [comment]
> > > Slh install, kurang modulenya🗿
> > 
> > 
> > Xiao, bantu fix web2mp4 atau fitur toimg, itu gabisa, dari website ezgif.com nya @ImYanXiao
> 
> [#158](https://github.com/ImYanXiao/Elaina-MultiDevice/pull/158)
> 
> Gw bantu sticker toimg

tetep ae gabisa

**Comment by ShirokamiRyzen** [comment]
> > > > Slh install, kurang modulenya🗿
> > > 
> > > 
> > > Xiao, bantu fix web2mp4 atau fitur toimg, itu gabisa, dari website ezgif.com nya @ImYanXiao
> > 
> > 
> > [#158](https://github.com/ImYanXiao/Elaina-MultiDevice/pull/158)
> > Gw bantu sticker toimg
> 
> tetep ae gabisa

![Screenshot_2024-03-15-18-23-13-64_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/76462435/c37c0127-7280-4e8d-9ddf-062257d85fe9)
Mana ada

**Comment by Xnuvers007** [comment]
> > > > > Slh install, kurang modulenya🗿
> > > > 
> > > > 
> > > > Xiao, bantu fix web2mp4 atau fitur toimg, itu gabisa, dari website ezgif.com nya @ImYanXiao
> > > 
> > > 
> > > [#158](https://github.com/ImYanXiao/Elaina-MultiDevice/pull/158)
> > > Gw bantu sticker toimg
> > 
> > 
> > tetep ae gabisa
> 
> ![Screenshot_2024-03-15-18-23-13-64_6012fa4d4ddec268fc5c7112cbb265e7](https://private-user-images.githubusercontent.com/76462435/313172195-c37c0127-7280-4e8d-9ddf-062257d85fe9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTY2MTYsIm5iZiI6MTcxMTIxNjMxNiwicGF0aCI6Ii83NjQ2MjQzNS8zMTMxNzIxOTUtYzM3YzAxMjctNzI4MC00ZThkLTlkZGYtMDYyMjU3ZDg1ZmU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE3NTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NmEyMDY0ZWZkOWIyZjRjNGJkMTFkNzU0MDEwOGE0M2NhMzFlYTRjYTViNDBmN2RlNGMwZmMzZGMwNTllNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVGGJ6BB9RcFrmVDFLRK_LyFDfFSgcq8Bn9pCyj3IAk) Mana ada

kok gw malah gini ya 🗿
Terjadi kesalahan: getaddrinfo ENOTFOUND web.whatsapp.net
![image](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/62522733/a8045cff-3cf5-4111-8ffc-baf5870f7863)
