### ISSUE TITLE
bg fitur play ama ytmp3 nya ga muncul audionya, ytmp4 masih bisa

### ISSUE THREAD

**Issue by waceera** [ImYanXiao/Elaina-MultiDevice#164]

**Comment by Xnuvers007** [comment]
> _No description provided._

itu dari packagenya si Bochilteam scrapper itu sendiri, kalo mau coba cek script ini, ada 2 download ytmp3, gw bikin 2 buat backup

**Comment by ImYanXiao** [comment]
> > _No description provided._
> 
> itu dari packagenya si Bochilteam scrapper itu sendiri, kalo mau coba cek script ini, ada 2 download ytmp3, gw bikin 2 buat backup

Mending tambahin button ga?🗿

**Comment by Xnuvers007** [comment]
> > > _No description provided._
> > 
> > 
> > itu dari packagenya si Bochilteam scrapper itu sendiri, kalo mau coba cek script ini, ada 2 download ytmp3, gw bikin 2 buat backup
> 
> Mending tambahin button ga?🗿

Mang bisa ? Bukannya dah dihapus ? Kalo bisa tambahin  aja, anu buatin pairing code by number sama QR aja biar enak (saran aja)

**Comment by ImYanXiao** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > itu dari packagenya si Bochilteam scrapper itu sendiri, kalo mau coba cek script ini, ada 2 download ytmp3, gw bikin 2 buat backup
> > 
> > 
> > Mending tambahin button ga?🗿
> 
> Mang bisa ? Bukannya dah dihapus ? Kalo bisa tambahin aja, anu buatin pairing code by number sama QR aja biar enak (saran aja)

Bisa, pke interactive

**Comment by ImYanXiao** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > itu dari packagenya si Bochilteam scrapper itu sendiri, kalo mau coba cek script ini, ada 2 download ytmp3, gw bikin 2 buat backup
> > 
> > 
> > Mending tambahin button ga?🗿
> 
> Mang bisa ? Bukannya dah dihapus ? Kalo bisa tambahin aja, anu buatin pairing code by number sama QR aja biar enak (saran aja)

Tambahin aja pke opts

**Comment by Xnuvers007** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > itu dari packagenya si Bochilteam scrapper itu sendiri, kalo mau coba cek script ini, ada 2 download ytmp3, gw bikin 2 buat backup
> > > 
> > > 
> > > Mending tambahin button ga?🗿
> > 
> > 
> > Mang bisa ? Bukannya dah dihapus ? Kalo bisa tambahin aja, anu buatin pairing code by number sama QR aja biar enak (saran aja)
> 
> Bisa, pke interactive

Xiao, Saran gw, hapus aja itu virtext kek menu, gw buka di wa web jadi kosong terus gw buka di andro sama desktop app jadi force close. di hapus aja ganti teks biasa atau hilangkan virtext
![image](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/62522733/9664ffc6-a011-4954-a0dd-5f3ec398f01a)

**Comment by Xnuvers007** [comment]
@ImYanXiao

**Comment by ImYanXiao** [comment]
> @ImYanXiao

Mending lu pc di wa gw, jarang buka gh jadi telat mulu responnya🗿

**Comment by Xnuvers007** [comment]
> > @ImYanXiao
> 
> Mending lu pc di wa gw, jarang buka gh jadi telat mulu responnya🗿

Send wa/Ig/tele sini

Nih Instagram gw : Indradwi.25

**Comment by Xnuvers007** [comment]
> > @ImYanXiao
> 
> Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿

Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank

**Comment by Xnuvers007** [comment]
> > @ImYanXiao
> 
> Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿

Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank di wa web juga

**Comment by ImYanXiao** [comment]
> > > @ImYanXiao
> > 
> > 
> > Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿
> 
> Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank

Adreply?

**Comment by waceera** [comment]
> > > > @ImYanXiao
> > > 
> > > 
> > > Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿
> > 
> > 
> > Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank
> 
> Adreply?

Bang, gw pake sc elaina gw ketik menu terus gw biarin, nah tadi oas gw buka wa gw ga bisa ngebuka, akhirnya gw hapus data

**Comment by ImYanXiao** [comment]
> > > > > @ImYanXiao
> > > > 
> > > > 
> > > > Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿
> > > 
> > > 
> > > Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank
> > 
> > 
> > Adreply?
> 
> Bang, gw pake sc elaina gw ketik menu terus gw biarin, nah tadi oas gw buka wa gw ga bisa ngebuka, akhirnya gw hapus data

Woilah cik kasih liat langsung kek mana dah, bingung gw drtd🗿

**Comment by ImYanXiao** [comment]
> > > > > @ImYanXiao
> > > > 
> > > > 
> > > > Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿
> > > 
> > > 
> > > Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank
> > 
> > 
> > Adreply?
> 
> Bang, gw pake sc elaina gw ketik menu terus gw biarin, nah tadi oas gw buka wa gw ga bisa ngebuka, akhirnya gw hapus data

Woilah dri kemarin gw bingung ternyata masalahnya cuman perkara quoted doang, hapus ae tuh quoted kelar masalahnya 🗿👍

**Comment by waceera** [comment]
> > > > > > @ImYanXiao
> > > > > 
> > > > > 
> > > > > Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿
> > > > 
> > > > 
> > > > Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank
> > > 
> > > 
> > > Adreply?
> > 
> > 
> > Bang, gw pake sc elaina gw ketik menu terus gw biarin, nah tadi oas gw buka wa gw ga bisa ngebuka, akhirnya gw hapus data
> 
> Woilah dri kemarin gw bingung ternyata masalahnya cuman perkara quoted doang, hapus ae tuh quoted kelar masalahnya 🗿👍

Sekarnag force close nya udh diperbaiki kan? Ooya btw fitur play nya diperbaiki cuy ga ada audionya

**Comment by ImYanXiao** [comment]
> > > > > > > @ImYanXiao
> > > > > > 
> > > > > > 
> > > > > > Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿
> > > > > 
> > > > > 
> > > > > Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank
> > > > 
> > > > 
> > > > Adreply?
> > > 
> > > 
> > > Bang, gw pake sc elaina gw ketik menu terus gw biarin, nah tadi oas gw buka wa gw ga bisa ngebuka, akhirnya gw hapus data
> > 
> > 
> > Woilah dri kemarin gw bingung ternyata masalahnya cuman perkara quoted doang, hapus ae tuh quoted kelar masalahnya 🗿👍
> 
> Sekarnag force close nya udh diperbaiki kan? Ooya btw fitur play nya diperbaiki cuy ga ada audionya

Hari hari🗿🗿🗿

**Comment by waceera** [comment]
> > > > > > > > @ImYanXiao
> > > > > > > 
> > > > > > > 
> > > > > > > Ha? Virtext? Gimana maksudnya? Ga mudeng gw🗿
> > > > > > 
> > > > > > 
> > > > > > Intinya ketika ketik .menu atau only developer gitu android, aplikasi desktop/PC langsung force close atau blank
> > > > > 
> > > > > 
> > > > > Adreply?
> > > > 
> > > > 
> > > > Bang, gw pake sc elaina gw ketik menu terus gw biarin, nah tadi oas gw buka wa gw ga bisa ngebuka, akhirnya gw hapus data
> > > 
> > > 
> > > Woilah dri kemarin gw bingung ternyata masalahnya cuman perkara quoted doang, hapus ae tuh quoted kelar masalahnya 🗿👍
> > 
> > 
> > Sekarnag force close nya udh diperbaiki kan? Ooya btw fitur play nya diperbaiki cuy ga ada audionya
> 
> Hari hari🗿🗿🗿

P maksut

**Comment by waceera** [comment]
Yasudah bang gw close duku, gw kasih saran tar
