### ISSUE TITLE
ngab .env buat ap?

### ISSUE THREAD

**Issue by HindiaFtNpc** [ImYanXiao/Elaina-MultiDevice#166]
nomor untuk bagian mana? apakah jika di hapus ttp aman?

**Comment by ImYanXiao** [comment]
@Xnuvers007 buat apaan? 🗿🗿🗿

**Comment by HindiaFtNpc** [comment]
lah🗿

**Comment by ImYanXiao** [comment]
> lah🗿

Mirip" lah sama global kegunaannya ya buat ngisi apikey, nomor dll bedanya cuman di bagian cara gunainnya

**Comment by HindiaFtNpc** [comment]
ya tau, cuman kek msi radak bingung aja gitu, di config juga kn ad

**Comment by HindiaFtNpc** [comment]
eek close ae lh lm bet jwb ny🗿

**Comment by ImYanXiao** [comment]
> eek close ae lh lm bet jwb ny🗿

Awoakoakakka ga bisa tiap hari buka gh njir🗿
