### ISSUE TITLE
Stiker

### ISSUE THREAD

**Issue by sneznat** [ImYanXiao/Elaina-MultiDevice#167]
Bang, sticker error?

**Comment by ImYanXiao** [comment]
> Bang, sticker error?

Error bagian mana?

**Comment by sneznat** [comment]
> > Bang, sticker error?
> 
> Error bagian mana?

Gak jadi bang, udah bisa :v
Padahal kemarin-kemarin error

**Comment by ImYanXiao** [comment]
> > > Bang, sticker error?
> > 
> > 
> > Error bagian mana?
> 
> Gak jadi bang, udah bisa :v Padahal kemarin-kemarin error

Mimetypenya jpeg kali🗿
