### ISSUE TITLE
saran

### ISSUE THREAD

**Issue by waceera** [ImYanXiao/Elaina-MultiDevice#168]
Bang? Ga niat buat button?

**Comment by ImYanXiao** [comment]
> Bang? Ga niat buat button?

Pertanyaan juga buat gw

**Comment by waceera** [comment]
> > Bang? Ga niat buat button?
> 
> Pertanyaan juga buat gw

Buat ae bang betonnya, biar kaga ketinggalan jaman

**Comment by ImYanXiao** [comment]
> > > Bang? Ga niat buat button?
> > 
> > 
> > Pertanyaan juga buat gw
> 
> Buat ae bang betonnya, biar kaga ketinggalan jaman

Beton Beton🗿

**Comment by eabdalmufid** [comment]
> > > Bang? Ga niat buat button?
> > 
> > 
> > Pertanyaan juga buat gw
> 
> Buat ae bang betonnya, biar kaga ketinggalan jaman

Percuma kalo ga keliatan di waweb

**Comment by waceera** [comment]
> > > > Bang? Ga niat buat button?
> > > 
> > > 
> > > Pertanyaan juga buat gw
> > 
> > 
> > Buat ae bang betonnya, biar kaga ketinggalan jaman
> 
> Percuma kalo ga keliatan di waweb

tapi keliatan juga buat user ios/android 😘

**Comment by waceera** [comment]
btw bang apikey lolhuman engror

**Comment by ImYanXiao** [comment]
> btw bang apikey lolhuman engror

Beli lah jir, mnada fri🗿

**Comment by waceera** [comment]
> > btw bang apikey lolhuman engror
> 
> Beli lah jir, mnada fri🗿

btw bang mending bot nya diinstall yt-search biar bisa diakses fitur youtubenya

**Comment by eabdalmufid** [comment]
> > > btw bang apikey lolhuman engror
> > 
> > 
> > Beli lah jir, mnada fri🗿
> 
> btw bang mending bot nya diinstall yt-search biar bisa diakses fitur youtubenya

Ambil scrape nya https://github.com/FatihArridho/Unofficial-YoutubeApi

**Comment by ImYanXiao** [comment]
> > > btw bang apikey lolhuman engror
> > 
> > 
> > Beli lah jir, mnada fri🗿
> 
> btw bang mending bot nya diinstall yt-search biar bisa diakses fitur youtubenya

Fitur play?

**Comment by waceera** [comment]
> > > > btw bang apikey lolhuman engror
> > > 
> > > 
> > > Beli lah jir, mnada fri🗿
> > 
> > 
> > btw bang mending bot nya diinstall yt-search biar bisa diakses fitur youtubenya
> 
> Fitur play?

ya,

**Comment by waceera** [comment]
> > > > > btw bang apikey lolhuman engror
> > > > 
> > > > 
> > > > Beli lah jir, mnada fri🗿
> > > 
> > > 
> > > btw bang mending bot nya diinstall yt-search biar bisa diakses fitur youtubenya
> > 
> > 
> > Fitur play?
> 
> ya,

Oiya bang plugin cekimel ama cariobat engror lagi 🗿

**Comment by Rusiko25** [comment]
> > > > btw bang apikey lolhuman engror
> > > 
> > > 
> > > Beli lah jir, mnada fri🗿
> > 
> > 
> > btw bang mending bot nya diinstall yt-search biar bisa diakses fitur youtubenya
> 
> Fitur play?

Bg lirik eror

**Comment by lolhumann25** [comment]
> > > > > btw bang apikey lolhuman engror
> > > > 
> > > > 
> > > > Beli lah jir, mnada fri🗿
> > > 
> > > 
> > > btw bang mending bot nya diinstall yt-search biar bisa diakses fitur youtubenya
> > 
> > 
> > Fitur play?
> 
> Bg lirik ama google eror

kembalikan daftar ama rpg

**Comment by HindiaFtNpc** [comment]
np sih org org pd gatel beton😂

**Comment by HindiaFtNpc** [comment]
> > > > btw bang apikey lolhuman engror
> > > 
> > > 
> > > Beli lah jir, mnada fri🗿
> > 
> > 
> > btw bang mending bot nya diinstall yt-search biar bisa diakses fitur youtubenya
> 
> Ambil scrape nya https://github.com/FatihArridho/Unofficial-YoutubeApi

terimakasih kawan

**Comment by ImYanXiao** [comment]
> np sih org org pd gatel beton😂

Heran juga gw🗿

**Comment by HindiaFtNpc** [comment]
> > np sih org org pd gatel beton😂
> 
> Heran juga gw🗿

folbek dong bg🗿😁

**Comment by ZTRdiamond** [comment]
sepuh berkumpul njirr😨

**Comment by HindiaFtNpc** [comment]
> sepuh berkumpul njirr😨

merendah gitu
