### ISSUE TITLE
Ngebug atau apa?

### ISSUE THREAD

**Issue by sneznat** [ImYanXiao/Elaina-MultiDevice#169]
Bang fitur addprem nya kok suka ilang-ilang sendiri ya? Pas udah di addprem terus beberapa jam udah ilang di listprem nya, kenapa tuh bang kira-kira?

**Comment by ImYanXiao** [comment]
> Bang fitur addprem nya kok suka ilang-ilang sendiri ya? Pas udah di addprem terus beberapa jam udah ilang di listprem nya, kenapa tuh bang kira-kira?

Awikwok 🗿🗿
