### ISSUE TITLE
error bang

### ISSUE THREAD

**Issue by hanipubaidur** [ImYanXiao/Elaina-MultiDevice#171]
bang, error ../lib/other-function.js nya mana jir,

**Comment by ImYanXiao** [comment]
> bang, error ../lib/other-function.js nya mana jir,

Lah, kode fitur yg mana tuh

**Comment by hanipubaidur** [comment]
ngga bang gajadi:V beda script soalnya:V

**Comment by hanipubaidur** [comment]
woiya bang, ada solusi ga buat ytdl github soya yg kudu verif captcha
