### ISSUE TITLE
Gak bisa di run

### ISSUE THREAD

**Issue by Raihanlimit** [ImYanXiao/Elaina-MultiDevice#174]
![Screenshot_2024-08-14-00-32-10-636_com android chrome](https://github.com/user-attachments/assets/cfdc50b3-97fd-4453-9101-c3580d4a1c58)
Bang ini kenapa ya kira-kira?

**Comment by ImYanXiao** [comment]
> ![Screenshot_2024-08-14-00-32-10-636_com android chrome](https://private-user-images.githubusercontent.com/89056745/357527821-cfdc50b3-97fd-4453-9101-c3580d4a1c58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTQ2NDUsIm5iZiI6MTcyMzU5NDM0NSwicGF0aCI6Ii84OTA1Njc0NS8zNTc1Mjc4MjEtY2ZkYzUwYjMtOTdmZC00NDUzLTkxMDEtYzM1ODBkNGExYzU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAwMTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjNlNzRiZjA3MDk3NDNkZGUwM2Q1YzIwMDViM2E3ZDdhZTEwMWIxMmZlZTc2ODBiZjNlMmEwMGIyMGJhOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXuRxfuZBggBCIR8cm73aaeK0DOBqzCvNK30oBh5XAk) Bang ini kenapa ya kira-kira?

V node js lama

**Comment by Raihanlimit** [comment]
> > ![Screenshot_2024-08-14-00-32-10-636_com android chrome](https://private-user-images.githubusercontent.com/89056745/357527821-cfdc50b3-97fd-4453-9101-c3580d4a1c58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTQ2NDUsIm5iZiI6MTcyMzU5NDM0NSwicGF0aCI6Ii84OTA1Njc0NS8zNTc1Mjc4MjEtY2ZkYzUwYjMtOTdmZC00NDUzLTkxMDEtYzM1ODBkNGExYzU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAwMTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjNlNzRiZjA3MDk3NDNkZGUwM2Q1YzIwMDViM2E3ZDdhZTEwMWIxMmZlZTc2ODBiZjNlMmEwMGIyMGJhOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXuRxfuZBggBCIR8cm73aaeK0DOBqzCvNK30oBh5XAk) Bang ini kenapa ya kira-kira?
> 
> V node js lama

Versi 20.12.2 nodejs nya

**Comment by Raihanlimit** [comment]
> > ![Screenshot_2024-08-14-00-32-10-636_com android chrome](https://private-user-images.githubusercontent.com/89056745/357527821-cfdc50b3-97fd-4453-9101-c3580d4a1c58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTQ2NDUsIm5iZiI6MTcyMzU5NDM0NSwicGF0aCI6Ii84OTA1Njc0NS8zNTc1Mjc4MjEtY2ZkYzUwYjMtOTdmZC00NDUzLTkxMDEtYzM1ODBkNGExYzU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAwMTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjNlNzRiZjA3MDk3NDNkZGUwM2Q1YzIwMDViM2E3ZDdhZTEwMWIxMmZlZTc2ODBiZjNlMmEwMGIyMGJhOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXuRxfuZBggBCIR8cm73aaeK0DOBqzCvNK30oBh5XAk) Bang ini kenapa ya kira-kira?
> 
> V node js lama

Udah bisa bang make versi 20.15.1

**Comment by Xnuvers007** [comment]
> > > ![Screenshot_2024-08-14-00-32-10-636_com android chrome](https://private-user-images.githubusercontent.com/89056745/357527821-cfdc50b3-97fd-4453-9101-c3580d4a1c58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTQ2NDUsIm5iZiI6MTcyMzU5NDM0NSwicGF0aCI6Ii84OTA1Njc0NS8zNTc1Mjc4MjEtY2ZkYzUwYjMtOTdmZC00NDUzLTkxMDEtYzM1ODBkNGExYzU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAwMTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjNlNzRiZjA3MDk3NDNkZGUwM2Q1YzIwMDViM2E3ZDdhZTEwMWIxMmZlZTc2ODBiZjNlMmEwMGIyMGJhOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXuRxfuZBggBCIR8cm73aaeK0DOBqzCvNK30oBh5XAk) Bang ini kenapa ya kira-kira?
> > 
> > 
> > V node js lama
> 
> Udah bisa bang make versi 20.15.1

Biasakan kalo udah solved, di tutup mas

**Comment by Raihanlimit** [comment]
> > > > ![Screenshot_2024-08-14-00-32-10-636_com android chrome](https://private-user-images.githubusercontent.com/89056745/357527821-cfdc50b3-97fd-4453-9101-c3580d4a1c58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTQ2NDUsIm5iZiI6MTcyMzU5NDM0NSwicGF0aCI6Ii84OTA1Njc0NS8zNTc1Mjc4MjEtY2ZkYzUwYjMtOTdmZC00NDUzLTkxMDEtYzM1ODBkNGExYzU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAwMTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjNlNzRiZjA3MDk3NDNkZGUwM2Q1YzIwMDViM2E3ZDdhZTEwMWIxMmZlZTc2ODBiZjNlMmEwMGIyMGJhOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXuRxfuZBggBCIR8cm73aaeK0DOBqzCvNK30oBh5XAk) Bang ini kenapa ya kira-kira?
> > > 
> > > 
> > > V node js lama
> > 
> > 
> > Udah bisa bang make versi 20.15.1
> 
> Biasakan kalo udah solved, di tutup mas

Iya bang saya lupa, maaf
