### ISSUE TITLE
Youtube scrape koid bg

### ISSUE THREAD

**Issue by ShirokamiRyzen** [ImYanXiao/Elaina-MultiDevice#175]
Haiyaaa
![image](https://github.com/user-attachments/assets/550b3f24-077b-44f6-9c55-c40a5fb8472c)

**Comment by ImYanXiao** [comment]
> Haiyaaa ![image](https://private-user-images.githubusercontent.com/76462435/358461976-550b3f24-077b-44f6-9c55-c40a5fb8472c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDIwNjksIm5iZiI6MTcyNDA0MTc2OSwicGF0aCI6Ii83NjQ2MjQzNS8zNTg0NjE5NzYtNTUwYjNmMjQtMDc3Yi00NGY2LTljNTUtYzQwYTVmYjg0NzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA0MjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MmRkNzg4MWU2YjhmODdhMDc4Njc0NWQ0MTBjMDUxOWQ0MjNjODhlMjg4MDBjMzFiMTA1ODNlNjA4ODYyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KKCL_PFOVurd56byRa3xTxsGhnOcdTCGGtOQB_Ci_uI)

Masuk akal

**Comment by ImYanXiao** [comment]
> Haiyaaa ![image](https://private-user-images.githubusercontent.com/76462435/358461976-550b3f24-077b-44f6-9c55-c40a5fb8472c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDEzNjAsIm5iZiI6MTcyNzg0MTA2MCwicGF0aCI6Ii83NjQ2MjQzNS8zNTg0NjE5NzYtNTUwYjNmMjQtMDc3Yi00NGY2LTljNTUtYzQwYTVmYjg0NzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDAzNTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNTU2YjY2NTYxOGY1MDdkZjAwOTAwYzY4OTA3MDY1ZTRkZmQ4MTZmYTg5MDA4NGQ5NTg3NzdjNjY2MmJjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U6d0pEkTYz6q4TGs2s54H8snu1Znb7fE3KKOS28PaLw)

Fix ya le

**Comment by ImYanXiao** [comment]
Closed
