### ISSUE TITLE
Di run malah kek gini

### ISSUE THREAD

**Issue by Vikazee** [ImYanXiao/Elaina-MultiDevice#177]
![IMG_20240821_182612](https://github.com/user-attachments/assets/e115f3d9-27a5-47b8-a6fc-a3d678bd71a6)

**Comment by ImYanXiao** [comment]
Killed..... Modulenya belum keinstall sepenuhnya

**Comment by Vikazee** [comment]
Jadi harus gimana?

**Comment by ImYanXiao** [comment]
> Jadi harus gimana? Padahal ga di apa apain

Emang ga di apa"in tp pas ditengah proses install module berhenti krn dipaksa berhenti dikarenakan mungkin saat proses berlangsung ram, disk atau cpu melebihi kapasitas yg disediakan makanya otomatis di berhentikan dan mau di start ya error karena modulenya aja ga lengkap🗿🗿🗿🗿
