### ISSUE TITLE
Fitur google bang.

### ISSUE THREAD

**Issue by KiyoEditz** [ImYanXiao/Elaina-MultiDevice#180]
Cek fitur google lu bang. Punya gua mokad, gak keluar teks. Siapa tau punya lu juga kena.

**Comment by ImYanXiao** [comment]
@Xnuvers007 bkn apikeynya kan? 🗿

**Comment by Xnuvers007** [comment]
> @Xnuvers007 bkn apikeynya kan? 🗿

🗿
Iya bikin apikey di serpdog🗿

belum buat/nemu 🗿

**Comment by Xnuvers007** [comment]
https://docs.serpdog.io/google-search-api

**Comment by ImYanXiao** [comment]
> https://docs.serpdog.io/google-search-api

Dog memang🗿🗿

**Comment by KiyoEditz** [comment]
Infokan kalok ke fix. Di gua belom soalnya:v. Kalok bisa jangan api sih.

**Comment by ImYanXiao** [comment]
> Infokan kalok ke fix. Di gua belom soalnya:v. Kalok bisa jangan api sih.

Cuman suruh ganti apikey itu bikin aja di web serpdog itu trs ganti
