### ISSUE TITLE
Gak bisa ngirim media dari beberapa respon link yang banyak

### ISSUE THREAD

**Issue by Raihanlimit** [ImYanXiao/Elaina-MultiDevice#181]
![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://github.com/user-attachments/assets/b98cdccf-37f6-45c3-a529-c9dec3662752)
Bang ini kenapa?

**Comment by ImYanXiao** [comment]
> ![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://private-user-images.githubusercontent.com/89056745/374165946-b98cdccf-37f6-45c3-a529-c9dec3662752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQ4MjEsIm5iZiI6MTcyODMwNDUyMSwicGF0aCI6Ii84OTA1Njc0NS8zNzQxNjU5NDYtYjk4Y2RjY2YtMzdmNi00NWMzLWE1MjktYzlkZWMzNjYyNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYwY2IwMjMyMjQ5MWVlNDQ4NDZlNGNmMTAzNmU4NDkwMTQ3MjczZmNiZDNjNTcyN2E2ODhiZDJlYjk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ilk9DpHUC5Uw79HD8JcPzbQmpUPcSuXvecw2s2At6uI) Bang ini kenapa?

Fitur mana tuh? 🤨

**Comment by Raihanlimit** [comment]
> > ![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://private-user-images.githubusercontent.com/89056745/374165946-b98cdccf-37f6-45c3-a529-c9dec3662752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQ4MjEsIm5iZiI6MTcyODMwNDUyMSwicGF0aCI6Ii84OTA1Njc0NS8zNzQxNjU5NDYtYjk4Y2RjY2YtMzdmNi00NWMzLWE1MjktYzlkZWMzNjYyNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYwY2IwMjMyMjQ5MWVlNDQ4NDZlNGNmMTAzNmU4NDkwMTQ3MjczZmNiZDNjNTcyN2E2ODhiZDJlYjk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ilk9DpHUC5Uw79HD8JcPzbQmpUPcSuXvecw2s2At6uI) Bang ini kenapa?
> 
> Fitur mana tuh? 🤨

Pinterest, gw pake scrape
Gw coba di bot gw satunya normal ( sc XM4ZE ), tapi gw coba di sc ini malah gitu. Kenapa tuh kira-kira?

**Comment by ImYanXiao** [comment]
> > > ![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://private-user-images.githubusercontent.com/89056745/374165946-b98cdccf-37f6-45c3-a529-c9dec3662752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQ4MjEsIm5iZiI6MTcyODMwNDUyMSwicGF0aCI6Ii84OTA1Njc0NS8zNzQxNjU5NDYtYjk4Y2RjY2YtMzdmNi00NWMzLWE1MjktYzlkZWMzNjYyNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYwY2IwMjMyMjQ5MWVlNDQ4NDZlNGNmMTAzNmU4NDkwMTQ3MjczZmNiZDNjNTcyN2E2ODhiZDJlYjk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ilk9DpHUC5Uw79HD8JcPzbQmpUPcSuXvecw2s2At6uI) Bang ini kenapa?
> > 
> > 
> > Fitur mana tuh? 🤨
> 
> Pinterest, gw pake scrape Gw coba di bot gw satunya normal ( sc XM4ZE ), tapi gw coba di sc ini malah gitu. Kenapa tuh kira-kira?

Hasil Urlnya kepanjangan kali

**Comment by Raihanlimit** [comment]
> > > > ![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://private-user-images.githubusercontent.com/89056745/374165946-b98cdccf-37f6-45c3-a529-c9dec3662752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQ4MjEsIm5iZiI6MTcyODMwNDUyMSwicGF0aCI6Ii84OTA1Njc0NS8zNzQxNjU5NDYtYjk4Y2RjY2YtMzdmNi00NWMzLWE1MjktYzlkZWMzNjYyNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYwY2IwMjMyMjQ5MWVlNDQ4NDZlNGNmMTAzNmU4NDkwMTQ3MjczZmNiZDNjNTcyN2E2ODhiZDJlYjk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ilk9DpHUC5Uw79HD8JcPzbQmpUPcSuXvecw2s2At6uI) Bang ini kenapa?
> > > 
> > > 
> > > Fitur mana tuh? 🤨
> > 
> > 
> > Pinterest, gw pake scrape Gw coba di bot gw satunya normal ( sc XM4ZE ), tapi gw coba di sc ini malah gitu. Kenapa tuh kira-kira?
> 
> Hasil Urlnya kepanjangan kali
Tapi gw pake base nya XM4ZE bisa bang, kalau pake base Elaina ini gak bisa
![IMG_20241009_143543](https://github.com/user-attachments/assets/1064b6da-d8e7-4b9e-8ac1-991e097f588e)
Yang kiri pake Elaina, yang kanan pake XM4ZE

**Comment by ImYanXiao** [comment]
> > > > > ![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://private-user-images.githubusercontent.com/89056745/374165946-b98cdccf-37f6-45c3-a529-c9dec3662752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQ4MjEsIm5iZiI6MTcyODMwNDUyMSwicGF0aCI6Ii84OTA1Njc0NS8zNzQxNjU5NDYtYjk4Y2RjY2YtMzdmNi00NWMzLWE1MjktYzlkZWMzNjYyNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYwY2IwMjMyMjQ5MWVlNDQ4NDZlNGNmMTAzNmU4NDkwMTQ3MjczZmNiZDNjNTcyN2E2ODhiZDJlYjk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ilk9DpHUC5Uw79HD8JcPzbQmpUPcSuXvecw2s2At6uI) Bang ini kenapa?
> > > > 
> > > > 
> > > > Fitur mana tuh? 🤨
> > > 
> > > 
> > > Pinterest, gw pake scrape Gw coba di bot gw satunya normal ( sc XM4ZE ), tapi gw coba di sc ini malah gitu. Kenapa tuh kira-kira?
> > 
> > 
> > Hasil Urlnya kepanjangan kali
> > Tapi gw pake base nya XM4ZE bisa bang, kalau pake base Elaina ini gak bisa
> > ![IMG_20241009_143543](https://private-user-images.githubusercontent.com/89056745/374855992-1064b6da-d8e7-4b9e-8ac1-991e097f588e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzY0NTIsIm5iZiI6MTcyODYzNjE1MiwicGF0aCI6Ii84OTA1Njc0NS8zNzQ4NTU5OTItMTA2NGI2ZGEtZDhlNy00YjllLThhYzEtOTkxZTA5N2Y1ODhlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4NDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZTFmODYwYmY0MmNlMTZkMzRhYzQ1YTA3NzFkNDYwMTJhZDZjNzYwZGU2OTE3ZDBmMjA1YTNmYjFkMzZhZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dlq8i94msSz8-2gWhFCRJl8ovW_w0Q-DyiPpndWlXgQ)
> > Yang kiri pake Elaina, yang kanan pake XM4ZE

Gw susah ngenalin errornya kalo cuman ss gitu cuy🗿

**Comment by Raihanlimit** [comment]
> > > > > > ![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://private-user-images.githubusercontent.com/89056745/374165946-b98cdccf-37f6-45c3-a529-c9dec3662752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQ4MjEsIm5iZiI6MTcyODMwNDUyMSwicGF0aCI6Ii84OTA1Njc0NS8zNzQxNjU5NDYtYjk4Y2RjY2YtMzdmNi00NWMzLWE1MjktYzlkZWMzNjYyNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYwY2IwMjMyMjQ5MWVlNDQ4NDZlNGNmMTAzNmU4NDkwMTQ3MjczZmNiZDNjNTcyN2E2ODhiZDJlYjk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ilk9DpHUC5Uw79HD8JcPzbQmpUPcSuXvecw2s2At6uI) Bang ini kenapa?
> > > > > 
> > > > > 
> > > > > Fitur mana tuh? 🤨
> > > > 
> > > > 
> > > > Pinterest, gw pake scrape Gw coba di bot gw satunya normal ( sc XM4ZE ), tapi gw coba di sc ini malah gitu. Kenapa tuh kira-kira?
> > > 
> > > 
> > > Hasil Urlnya kepanjangan kali
> > > Tapi gw pake base nya XM4ZE bisa bang, kalau pake base Elaina ini gak bisa
> > > ![IMG_20241009_143543](https://private-user-images.githubusercontent.com/89056745/374855992-1064b6da-d8e7-4b9e-8ac1-991e097f588e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzY0NTIsIm5iZiI6MTcyODYzNjE1MiwicGF0aCI6Ii84OTA1Njc0NS8zNzQ4NTU5OTItMTA2NGI2ZGEtZDhlNy00YjllLThhYzEtOTkxZTA5N2Y1ODhlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4NDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZTFmODYwYmY0MmNlMTZkMzRhYzQ1YTA3NzFkNDYwMTJhZDZjNzYwZGU2OTE3ZDBmMjA1YTNmYjFkMzZhZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dlq8i94msSz8-2gWhFCRJl8ovW_w0Q-DyiPpndWlXgQ)
> > > Yang kiri pake Elaina, yang kanan pake XM4ZE
> 
> Gw susah ngenalin errornya kalo cuman ss gitu cuy🗿

Terus gimana bang? Mau gw kirim full logs error nya atau kodenya?🐦

**Comment by ImYanXiao** [comment]
> > > > > > > ![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://private-user-images.githubusercontent.com/89056745/374165946-b98cdccf-37f6-45c3-a529-c9dec3662752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQ4MjEsIm5iZiI6MTcyODMwNDUyMSwicGF0aCI6Ii84OTA1Njc0NS8zNzQxNjU5NDYtYjk4Y2RjY2YtMzdmNi00NWMzLWE1MjktYzlkZWMzNjYyNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYwY2IwMjMyMjQ5MWVlNDQ4NDZlNGNmMTAzNmU4NDkwMTQ3MjczZmNiZDNjNTcyN2E2ODhiZDJlYjk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ilk9DpHUC5Uw79HD8JcPzbQmpUPcSuXvecw2s2At6uI) Bang ini kenapa?
> > > > > > 
> > > > > > 
> > > > > > Fitur mana tuh? 🤨
> > > > > 
> > > > > 
> > > > > Pinterest, gw pake scrape Gw coba di bot gw satunya normal ( sc XM4ZE ), tapi gw coba di sc ini malah gitu. Kenapa tuh kira-kira?
> > > > 
> > > > 
> > > > Hasil Urlnya kepanjangan kali
> > > > Tapi gw pake base nya XM4ZE bisa bang, kalau pake base Elaina ini gak bisa
> > > > ![IMG_20241009_143543](https://private-user-images.githubusercontent.com/89056745/374855992-1064b6da-d8e7-4b9e-8ac1-991e097f588e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzY0NTIsIm5iZiI6MTcyODYzNjE1MiwicGF0aCI6Ii84OTA1Njc0NS8zNzQ4NTU5OTItMTA2NGI2ZGEtZDhlNy00YjllLThhYzEtOTkxZTA5N2Y1ODhlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4NDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZTFmODYwYmY0MmNlMTZkMzRhYzQ1YTA3NzFkNDYwMTJhZDZjNzYwZGU2OTE3ZDBmMjA1YTNmYjFkMzZhZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dlq8i94msSz8-2gWhFCRJl8ovW_w0Q-DyiPpndWlXgQ)
> > > > Yang kiri pake Elaina, yang kanan pake XM4ZE
> > 
> > 
> > Gw susah ngenalin errornya kalo cuman ss gitu cuy🗿
> 
> Terus gimana bang? Mau gw kirim full logs error nya atau kodenya?🐦

Send ae kodene tak coba eval🗿

**Comment by ImYanXiao** [comment]
Nomer gw masih sama🗿

**Comment by Raihanlimit** [comment]
> > > > > > > > ![Screenshot_2024-10-07-19-20-52-724_com whatsapp](https://private-user-images.githubusercontent.com/89056745/374165946-b98cdccf-37f6-45c3-a529-c9dec3662752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQ4MjEsIm5iZiI6MTcyODMwNDUyMSwicGF0aCI6Ii84OTA1Njc0NS8zNzQxNjU5NDYtYjk4Y2RjY2YtMzdmNi00NWMzLWE1MjktYzlkZWMzNjYyNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWYwY2IwMjMyMjQ5MWVlNDQ4NDZlNGNmMTAzNmU4NDkwMTQ3MjczZmNiZDNjNTcyN2E2ODhiZDJlYjk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ilk9DpHUC5Uw79HD8JcPzbQmpUPcSuXvecw2s2At6uI) Bang ini kenapa?
> > > > > > > 
> > > > > > > 
> > > > > > > Fitur mana tuh? 🤨
> > > > > > 
> > > > > > 
> > > > > > Pinterest, gw pake scrape Gw coba di bot gw satunya normal ( sc XM4ZE ), tapi gw coba di sc ini malah gitu. Kenapa tuh kira-kira?
> > > > > 
> > > > > 
> > > > > Hasil Urlnya kepanjangan kali
> > > > > Tapi gw pake base nya XM4ZE bisa bang, kalau pake base Elaina ini gak bisa
> > > > > ![IMG_20241009_143543](https://private-user-images.githubusercontent.com/89056745/374855992-1064b6da-d8e7-4b9e-8ac1-991e097f588e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzY0NTIsIm5iZiI6MTcyODYzNjE1MiwicGF0aCI6Ii84OTA1Njc0NS8zNzQ4NTU5OTItMTA2NGI2ZGEtZDhlNy00YjllLThhYzEtOTkxZTA5N2Y1ODhlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4NDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZTFmODYwYmY0MmNlMTZkMzRhYzQ1YTA3NzFkNDYwMTJhZDZjNzYwZGU2OTE3ZDBmMjA1YTNmYjFkMzZhZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dlq8i94msSz8-2gWhFCRJl8ovW_w0Q-DyiPpndWlXgQ)
> > > > > Yang kiri pake Elaina, yang kanan pake XM4ZE
> > > 
> > > 
> > > Gw susah ngenalin errornya kalo cuman ss gitu cuy🗿
> > 
> > 
> > Terus gimana bang? Mau gw kirim full logs error nya atau kodenya?🐦
> 
> Send ae kodene tak coba eval🗿

Okee

**Comment by Raihanlimit** [comment]
> Nomer gw masih sama🗿

Yang belakangnya 8354?

**Comment by ImYanXiao** [comment]
> > Nomer gw masih sama🗿
> 
> Yang belakangnya 8354?

Hooh

**Comment by Raihanlimit** [comment]
> > > Nomer gw masih sama🗿
> > 
> > 
> > Yang belakangnya 8354?
> 
> Hooh

Otw

**Comment by ImYanXiao** [comment]
Close, resolved.
