### ISSUE TITLE
QR MULTI AUTH 

### ISSUE THREAD

**Issue by BOTCAHX** [ImYanXiao/Elaina-MultiDevice#20]
> Untuk ambil sesinya bisa di sini :v

> GET SESSIONS
[Url](https://replit.com/@tioclkp02/Sessions-Multi-Auth) 

#12 line

**Comment by ImYanXiao** [comment]
Yu mek mi strong 🗿

**Comment by BOTCAHX** [comment]
> Yu mek mi strong 🗿

😎😎😎😎
