### ISSUE TITLE
cara ambil sesi gmana brh

### ISSUE THREAD

**Issue by BLXB567** [ImYanXiao/Elaina-MultiDevice#28]

**Comment by Yuri-Neko** [comment]
> _No description provided._



> _No description provided._

replit kan bisa

**Comment by BLXB567** [comment]
ga bisa om

**Comment by Yuri-Neko** [comment]
> ga bisa om

?apany yg g bsa

**Comment by Yuri-Neko** [comment]
> ga bisa om

gw bisa ambil multi session di replit

**Comment by BLXB567** [comment]
gw ga bisa mindah ke base replit

**Comment by ImYanXiao** [comment]
Apa nich

**Comment by ImYanXiao** [comment]
Replit bisa + support uptimerobot 🗿

**Comment by ImYanXiao** [comment]
Di Termux Bisa jg sih kucoba 🗿
