### ISSUE TITLE
Error ga bisa connect

### ISSUE THREAD

**Issue by Denz4323** [ImYanXiao/Elaina-MultiDevice#37]
Kalo pake main.js yg enc, ga bisa connect gagal Mulu, kalo pake main.js yg no enc error new function atau apa lah, ga bisa baca usesingleauth di main.js

**Comment by diki6969** [comment]
Ga connect mulu dah

**Comment by ImYanXiao** [comment]
> Ga connect mulu dah

Ga connect gimana bro?
