### ISSUE TITLE
CARA ADD PREM

### ISSUE THREAD

**Issue by irhanftelis** [ImYanXiao/Elaina-MultiDevice#38]
Cara add prem gmna bang?

**Comment by ImYanXiao** [comment]
.addprem tag orgnya 1D org 7D N more....

**Comment by irhanftelis** [comment]
oke om makasih

**Comment by irhanftelis** [comment]
saran adain fitur baru dong om lebih banyak lagi ngueheehe
thanks om sebelumnya
