### ISSUE TITLE
bang kalo pengen nambahin fitur apa aja ya yg perlu diubah

### ISSUE THREAD

**Issue by irhanftelis** [ImYanXiao/Elaina-MultiDevice#41]

**Comment by ImYanXiao** [comment]
Tergantung Orangnya :v

**Comment by ImYanXiao** [comment]
gada sih, cmn nambahin code ke file aja

**Comment by irhanftelis** [comment]
sc yang mana om yang harus ditambahin code nya?



Pada tanggal Jum, 3 Feb 2023 pukul 18.13 Xiao Yan? ***@***.***>
menulis:

**Comment by ImYanXiao** [comment]
Kurang Tau Kalo Sc 🗿
