### ISSUE TITLE
Slow Respon

### ISSUE THREAD

**Issue by diki6969** [ImYanXiao/Elaina-MultiDevice#48]
Entah Kenapa Versi Sekarang Ini Malah Slow Respon Dibanding Sebelumnya

**Comment by ImYanXiao** [comment]
Tergantung tempat run...

**Comment by diki6969** [comment]
Tapi sebelumnya gw run didoprax biasa aja bang masih fast respon

**Comment by ImYanXiao** [comment]
Kurang tw klo doprax, blm nyoba saya
