### ISSUE TITLE
BACOT

### ISSUE THREAD

**Issue by irhanftelis** [ImYanXiao/Elaina-MultiDevice#49]
![image](https://user-images.githubusercontent.com/63201597/218291065-8c0020cd-b00c-41e7-aee6-aa95e2d787de.png)
 
MENU BACOT GA KEKIRIM KE CLIENT

misall ada orang ngetik .bacot tapii quotes nya ga kekirim ke orang itu tapi malah ke kirim ke diri sendiri, dan ketika seseorang ngetik owner juga sama aja kekirim nya ke diri sendiri

**Comment by irhanftelis** [comment]
![image](https://user-images.githubusercontent.com/63201597/218293323-0080f9f3-7968-4b74-92f6-2548bd8197c8.png)

bug nya udh ketauan om klo buka di pc nongol tapi klo di hp ga nongol. cara fix nya gimana??

**Comment by ImYanXiao** [comment]
Masih pakai single session?

**Comment by ImYanXiao** [comment]
Bahkan bot saya pun terkadang juga gitu, tapi bedanya kekirim juga ke user dan kekirim ke nomor sendiri

**Comment by ImYanXiao** [comment]
Yu
