### ISSUE TITLE
disable

### ISSUE THREAD

**Issue by irhanftelis** [ImYanXiao/Elaina-MultiDevice#55]
cara nge disable fitur anticall gmna?

**Comment by ImYanXiao** [comment]
File handler.js bagian db.data.settings[this.user.jid].anticall

**Comment by irhanftelis** [comment]
Bang mau nanya lagi


![Screenshot_2023-03-12-13-44-52-953_com whatsapp](https://user-images.githubusercontent.com/63201597/224528965-9c89fd64-d664-41b0-8ed0-72b9b87db5a2.jpg)


Ini gmna ya kok pesan nya ga ke krim ke user. Pdhl di cek di wa bot sudah ke kirim tapi di user gaada.
![Screenshot_2023-03-12-13-44-48-376_com whatsapp w4b](https://user-images.githubusercontent.com/63201597/224528972-550b9841-a041-4987-9271-ab2276dd7194.jpg)

**Comment by ImYanXiao** [comment]
Run dmn? Klo replit coba ganti menunya biar ngga berat

**Comment by irhanftelis** [comment]
Replit, ganti menu gmna maksudnya om

**Comment by ImYanXiao** [comment]
> Replit, ganti menu gmna maksudnya om

Dibagian folder plugins file menu.js kan nanti ada model menu yg udh saya sediakan klo misal ada kendala seperti masalahmu 🙌

**Comment by ImYanXiao** [comment]
Pindahin // Ke line menu yg dipake sebelumnya kalo mau ganti yg lain
