### ISSUE TITLE
Button gak muncul di wa ori terbaru

### ISSUE THREAD

**Issue by ShirokamiRyzen** [ImYanXiao/Elaina-MultiDevice#59]
bang, tolong diupdate plugin menu nya, di versi terbaru whatsapp udah gabisa munculin chat yang ada buttonnya

**Comment by ImYanXiao** [comment]
> bang, tolong diupdate plugin menu nya, di versi terbaru whatsapp udah gabisa munculin chat yang ada buttonnya

Awikwok, yowes kapan" sy ganti menunya ☝🗿

**Comment by ShirokamiRyzen** [comment]
mantap cuy, ditunggu 👌

**Comment by ImYanXiao** [comment]
> mantap cuy, ditunggu 👌

Udah dri semalam :v

**Comment by ShirokamiRyzen** [comment]
form register usernya masih gabisa bang, masih pake button
