### ISSUE TITLE
qr

### ISSUE THREAD

**Issue by alvino-prog** [ImYanXiao/Elaina-MultiDevice#70]
qr di vps ga muncul banh

**Comment by Xnuvers007** [comment]
> qr di vps ga muncul banh

coba di ss bang, kagak ngerti errornya, mana bisa di fix :(

**Comment by alvino-prog** [comment]
Error gada, stuck

**Comment by alvino-prog** [comment]
![Screenshot 2023-04-12 162719](https://user-images.githubusercontent.com/54900965/231415932-1fc33586-1293-4696-96cb-82eff411df83.png)

**Comment by Xnuvers007** [comment]
> ![Screenshot 2023-04-12 162719](https://user-images.githubusercontent.com/54900965/231415932-1fc33586-1293-4696-96cb-82eff411df83.png)

hapus semua file yang ada di folder sessions, habis itu coba lagi

**Comment by Xnuvers007** [comment]
pastikan gitclone dulu untuk yang terbaru

**Comment by alvino-prog** [comment]
Udh banh

**Comment by alvino-prog** [comment]
seesion nya kosong
sebelum nya bisa, pas clone lg yg baru skrng ga muncul

**Comment by alvino-prog** [comment]
done bisa tq
