### ISSUE TITLE
error install module

### ISSUE THREAD

**Issue by ngewa** [ImYanXiao/Elaina-MultiDevice#82]
![Screenshot_20230427-124308_Termux](https://user-images.githubusercontent.com/92763809/234769845-2d343aa5-cb26-4c8e-b62d-adcde4528839.jpg)

**Comment by ImYanXiao** [comment]
Jan install di termux bang😔☝

> ![Screenshot_20230427-124308_Termux](https://user-images.githubusercontent.com/92763809/234769845-2d343aa5-cb26-4c8e-b62d-adcde4528839.jpg)

**Comment by ImYanXiao** [comment]
> itu install di vps js versi 17.3.0

Oiya w ga liat itu bagian usernya jdi root

**Comment by ImYanXiao** [comment]
pas npm i?

**Comment by Xnuvers007** [comment]
> > pas npm i?
> 
> iya

Coba gini

npm cache clean --force
npm install --force
npm update --force
npm audit fix --force

**Comment by diki6969** [comment]
Pake yarn install mungkin
