### ISSUE TITLE
QR GAK MUNCUL

### ISSUE THREAD

**Issue by Raihanlimit** [ImYanXiao/Elaina-MultiDevice#86]
![Screenshot_2023-05-07-09-31-42-80](https://user-images.githubusercontent.com/89056745/236654580-3b75664b-b597-4843-a810-f4620230923f.jpg)

**Comment by ImYanXiao** [comment]
Hamdeh, baiklah masalah ini lagi🗿

**Comment by ImYanXiao** [comment]
> ![Screenshot_2023-05-07-09-31-42-80](https://user-images.githubusercontent.com/89056745/236654580-3b75664b-b597-4843-a810-f4620230923f.jpg)

Gw nyoba di panelnya Tio bisa

**Comment by ImYanXiao** [comment]
![Uploading Screenshot_2023-05-08-07-45-54-086_com.android.chrome.jpg…]()

**Comment by ImYanXiao** [comment]
![Uploading Screenshot_2023-05-08-07-45-54-086_com.android.chrome.jpg…]()

**Comment by ImYanXiao** [comment]
![Screenshot_2023-05-08-07-49-28-852_com android chrome](https://user-images.githubusercontent.com/102222065/236711694-1c4f1332-627a-4c39-9000-5f4f8f12efe5.jpg)
Perasaan bisa dah

**Comment by ImYanXiao** [comment]
@BOTCAHX

**Comment by OxBrutal** [comment]
> ![Screenshot_2023-05-07-09-31-42-80](https://user-images.githubusercontent.com/89056745/236654580-3b75664b-b597-4843-a810-f4620230923f.jpg)

Sama puh gamuncul dipanel gw 🗿

**Comment by OxBrutal** [comment]
Dipanelku jga gamuncul puh 🗿

**Comment by Raihanlimit** [comment]
> Dipanelku jga gamuncul puh 🗿

Gw pake SC ori nya bisa muncul QR nya, tapi pake SC gw sendiri gak bisa muncul QR nya bjir😔☝️
