### ISSUE TITLE
LEMOT

### ISSUE THREAD

**Issue by irhanftelis** [ImYanXiao/Elaina-MultiDevice#93]
NAMBAH LEMOT KHUSUSNYA PAS RUN DI REPLIT

**Comment by Ahyad08** [comment]
Iya sih, pake panel 8gb pun masih lemot, lambat, slow respon

**Comment by Julius-Ulee** [comment]
> Iya sih, pake panel 8gb pun masih lemot, lambat, slow respon

pake heroku sir

**Comment by ImYanXiao** [comment]
Waduh, apa mending dibikin simple bot wea aja ya? Rpgnya dihilangin😂

**Comment by irhanftelis** [comment]
NAHHH, jadiin simpel bot wa aja om, biar ga lemot, penting fitur2 penting jangan diilangin kaya buat download video buat stiker dll aman

**Comment by Julius-Ulee** [comment]
> NAHHH, jadiin simpel bot wa aja om, biar ga lemot, penting fitur2 penting jangan diilangin kaya buat download video buat stiker dll aman

kali ini diriku setuju, lebih fokus ke grup, sticker, announcement, dan downloader tanpa menggunakan API karena banyak yg gk work ujung ujungnya gk bertahan lama

**Comment by ImYanXiao** [comment]
Yasudah kapan" Klo lagi niat🤣

**Comment by irhanftelis** [comment]
Elah gua nunggu dri kmren2 kirain lgi di kerjain ternyata baru dilirik😭

**Comment by ImYanXiao** [comment]
> Elah gua nunggu dri kmren2 kirain lgi di kerjain ternyata baru dilirik😭

Lgi sibuk ngab🗿

**Comment by irhanftelis** [comment]
Kabarin kalo udah jdi om hehe

**Comment by ImYanXiao** [comment]
> Kabarin kalo udah jdi om hehe

Gw close issues ini, klo masih ya open aja gpp
