### ISSUE TITLE
Error pada saat install dan tidak bisa scan QR 

### ISSUE THREAD

**Issue by KiyoEditz** [ImYanXiao/Elaina-MultiDevice#99]
Coba deploy di replit gak work, ada tulisan katanya versi JS gak support, coba deploy di optik link gagal scan terus, udah install ulang Sampek 5 kali scan ulang Sampek 20 kali, tetep gak bisa, bahkan Sampek ganti no wa nya juga, segera di perbaiki ok

**Comment by Raihanlimit** [comment]
Coba bang pas udah scan langsung restart/run ulang, kayak gw kemarin² gak bisa scan terus gw coba scan dan restart panelnya langsung bisa :v

**Comment by KiyoEditz** [comment]
> Coba bang pas udah scan langsung restart/run ulang, kayak gw kemarin² gak bisa scan terus gw coba scan dan restart panelnya langsung bisa :v

Kalok langsung restart bukan nya bakal langsung close ya sesi nya, soal nya ini gak bisa nya itu error koneksi nya.

**Comment by Raihanlimit** [comment]
> > Coba bang pas udah scan langsung restart/run ulang, kayak gw kemarin² gak bisa scan terus gw coba scan dan restart panelnya langsung bisa :v
> 
> Kalok langsung restart bukan nya bakal langsung close ya sesi nya, soal nya ini gak bisa nya itu error koneksi nya.

![IMG_20230701_033314](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/89056745/3bf28971-62f0-4676-9651-ad87fe832ac5)


Eror nya kayak gitu gak pas scan?

**Comment by KiyoEditz** [comment]
> > > Coba bang pas udah scan langsung restart/run ulang, kayak gw kemarin² gak bisa scan terus gw coba scan dan restart panelnya langsung bisa :v
> > 
> > 
> > Kalok langsung restart bukan nya bakal langsung close ya sesi nya, soal nya ini gak bisa nya itu error koneksi nya.
> 
> ![IMG_20230701_033314](https://user-images.githubusercontent.com/89056745/250194166-3bf28971-62f0-4676-9651-ad87fe832ac5.jpg)
> 
> Eror nya kayak gitu gak pas scan?

Iya kek gitu, dan sesi di wa nya juga gak keluar

**Comment by Raihanlimit** [comment]
Iya itu harus di restart, pas scan kan bakal muter dulu tuh di WA, nah pas masih muter langsung restart aja kayak gw dan nanti bakal bisa kok ( kalau gak bisa ya kurang tawu )

**Comment by KiyoEditz** [comment]
> Iya itu harus di restart, pas scan kan bakal muter dulu tuh di WA, nah pas masih muter langsung restart aja kayak gw dan nanti bakal bisa kok ( kalau gak bisa ya kurang tawu )

Ok lah, thanks saran nya, moga aja segera di fix sama bang YanXiao

**Comment by Julius-Ulee** [comment]
apa cuma aku yang masih gak bisa  :v

**Comment by Xnuvers007** [comment]
> apa cuma aku yang masih gak bisa :v

Take/fork aja nih SC dari gw
https://replit.com/@Xnuvers007/Xnuvers007botZ

**Comment by Xnuvers007** [comment]
> > Iya itu harus di restart, pas scan kan bakal muter dulu tuh di WA, nah pas masih muter langsung restart aja kayak gw dan nanti bakal bisa kok ( kalau gak bisa ya kurang tawu )
> 
> Ok lah, thanks saran nya, moga aja segera di fix sama bang YanXiao

take aja sc punya gw
https://replit.com/@Xnuvers007/Xnuvers007botZ

**Comment by Xnuvers007** [comment]
> > Iya itu harus di restart, pas scan kan bakal muter dulu tuh di WA, nah pas masih muter langsung restart aja kayak gw dan nanti bakal bisa kok ( kalau gak bisa ya kurang tawu )
> 
> Ok lah, thanks saran nya, moga aja segera di fix sama bang YanXiao

Take aja nih sc dari gw
https://replit.com/@Deployers/Xnuvers007botZ

udah up to date , ganti di bagian config aja atau bebas

**Comment by Xnuvers007** [comment]
> apa cuma aku yang masih gak bisa :v

Take aja nih sc dari gw
https://replit.com/@Deployers/Xnuvers007botZ

udah up to date , ganti di bagian config aja atau bebas

**Comment by Julius-Ulee** [comment]
> > apa cuma aku yang masih gak bisa :v
> 
> Take aja nih sc dari gw https://replit.com/@Deployers/Xnuvers007botZ
> 
> udah up to date , ganti di bagian config aja atau bebas

akhirnya ada penyelamat wkwk

**Comment by sshaxor** [comment]
Banyak yg ga work yah. API nya dll jg

**Comment by KiyoEditz** [comment]
> Banyak yg ga work yah. API nya dll jg

Iya nih, saya aja lagi nungguin update biar bisa makek

**Comment by Xnuvers007** [comment]
> Banyak yg ga work yah. API nya dll jg

bisa kasih tau yang apa aja ?

**Comment by Raihanlimit** [comment]
> Banyak yg ga work yah. API nya dll jg

Gw pake API xzn.wtf work

**Comment by Xnuvers007** [comment]
> > Banyak yg ga work yah. API nya dll jg
> 
> Gw pake API xzn.wtf work

nah bener, ini udah gw taro [Disini](https://github.com/ImYanXiao/Elaina-MultiDevice/blob/master/plugins/downloader-all.js#L1-L5)

**Comment by ImYanXiao** [comment]
> Coba deploy di replit gak work, ada tulisan katanya versi JS gak support, coba deploy di optik link gagal scan terus, udah install ulang Sampek 5 kali scan ulang Sampek 20 kali, tetep gak bisa, bahkan Sampek ganti no wa nya juga, segera di perbaiki ok

Next Time klw pairingCode Baileys udh fix pake pairingCode aja biar enak pakai 1 hp aja gaperlu scan" Pakai hp lain

**Comment by ImYanXiao** [comment]
Via login udh fix, saya coba jg udah bisa, cmn kurang recommended jdi nggak saya up

**Comment by apriansyah30** [comment]
![Screenshot_2023-07-28-21-38-36-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ImYanXiao/Elaina-MultiDevice/assets/137929096/a7471184-b0a0-41e6-ab7a-1872252cc67b)

ini kenapa dah kok ginii

**Comment by apriansyah30** [comment]
njir gw nemu cara aneh tapi nyata,ngambil file creds.json dri sc lain trus di masukin file session nya sc ini,tiba" conect sendiri ke wa,sumpah ini diluar nalar anjr gw niatnya cuma coba" trus gw kira gabisa eh pas gw tinggal tiba" ada bot muncul di gc namanya elaina anjrlah

**Comment by Julius-Ulee** [comment]
> njir gw nemu cara aneh tapi nyata,ngambil file creds.json dri sc lain trus di masukin file session nya sc ini,tiba" conect sendiri ke wa,sumpah ini diluar nalar anjr gw niatnya cuma coba" trus gw kira gabisa eh pas gw tinggal tiba" ada bot muncul di gc namanya elaina anjrlah

mungkin itu session ownernya der

**Comment by ImYanXiao** [comment]
> > njir gw nemu cara aneh tapi nyata,ngambil file creds.json dri sc lain trus di masukin file session nya sc ini,tiba" conect sendiri ke wa,sumpah ini diluar nalar anjr gw niatnya cuma coba" trus gw kira gabisa eh pas gw tinggal tiba" ada bot muncul di gc namanya elaina anjrlah
> 
> mungkin itu session ownernya der

Bkn

**Comment by Julius-Ulee** [comment]
walah kirain

**Comment by Xnuvers007** [comment]
> Coba deploy di replit gak work, ada tulisan katanya versi JS gak support, coba deploy di optik link gagal scan terus, udah install ulang Sampek 5 kali scan ulang Sampek 20 kali, tetep gak bisa, bahkan Sampek ganti no wa nya juga, segera di perbaiki ok

Udah fix yah, silahkan liat Readme.md terbaru dan package.json nya kembali, thx
